#!/usr/bin/bash

function	install_grub()
{
	pinfo "Installing GRUB"
	dset "Installing GRUB"

	lfs_virtualfs_enable
	do_chroot "grub-install ${TARGET_DISK} --target=i386-pc"
}

function	configure_grub()
{
	local	grub_dir="${LFS}/boot/grub"
	local	grub_cfg="${grub_dir}/grub.cfg"

	_mkdir "${grub_dir}"
	install_grub
	# envsubst NEED single quote
	# shellcheck disable=SC2016
	cat_default_file "${grub_cfg}" \
		< <(envsubst '$TARGET_DISK,$LFS_VMLINUZ,$LFS_DISTRO_DESC,$LINUX_VERSION,$LFS_DISTRO_VERSION,$LFS_DISTRO_CODENAME' \
			< "${DIR_FILE}/grub/lfs")
}
