#!/usr/bin/bash

function	configure_grub()
{
	local	grub_dir="${LFS}/boot/grub"
	local	grub_cfg="${grub_dir}/grub.cfg"
	local	grub_device="${TARGET_DISK}"

	_mkdir "${grub_dir}"
	do_chroot "grub-install ${grub_device}"
	# envsubst NEED single quote
	# shellcheck disable=SC2016
	cat_default_file "${grub_cfg}" \
		< <(envsubst '$TARGET_DISK,$LFS_VMLINUZ,$LFS_DISTRO_DESC,$LINUX_VERSION,$LFS_DISTRO_VERSION,$LFS_DISTRO_CODENAME' \
			< "${DIR_FILE}/grub/lfs")
}
