#!/usr/bin/bash

function	finish_touch()
{
	# Create /etc/lfs-release, /etc/lsb-release, and /etc/os-release
	echo "${LFS_DISTRO_VERSION}" > "${LFS}/etc/lfs-release"

	# envsubst NEED single quote
	# shellcheck disable=SC2016
	envsubst '$LFS_DISTRO,$LFS_DISTRO_VERSION,$LFS_DISTRO_CODENAME,$LFS_DISTRO_DESC' \
		> "${LFS}/etc/lsb-release" \
		< "${DIR_FILE}/lsb-release"

	# envsubst NEED single quote
	# shellcheck disable=SC2016
	envsubst '$LFS_DISTRO_DESC,$LFS_DISTRO_VERSION,$LFS_DISTRO_MINI,$LFS_DISTRO_CODENAME,$LFS_DISTRO_HOME' \
		> "${LFS}/etc/os-release" \
		< "${DIR_FILE}/os-release"

	# Remove history files
	find "${LFS}" -type f -name ".*_history" -exec rm -f {} \; || true

	# Change root passwd
	do_chroot "echo 'root:${LFS_ROOT_PASS}' | chpasswd"
	create_user
}
