#!/bin/bash

function	change_ownership()
{
	pinfo "Changing ownership of ${LFS} to root"
	chown -R root:root ${LFS}/{usr,lib,var,etc,bin,sbin,tools}
	case $(uname -m) in
		x86_64) chown -R root:root ${LFS}/lib64 ;;
	esac
}
