#!/bin/bash

function	compile_python_pass1()
{
	package_init python 0.5

	do_chroot "cd /sources/${package_tar_folder} \
	&&./configure --prefix=/usr \
		--enable-shared \
		--without-ensurepip \
	&& make \
	&& make install"

	package_clean
}
