#!/bin/bash

function	compile_texinfo_pass1()
{
	package_init texinfo 0.2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
	&& make \
	&& make install"

	package_clean
}
