#!/bin/bash

function	compile_bison_pass1()
{
	local	dst_dir="bison-3.8.2"
	local	sbu="0.2"
	local	package="bison"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} pass 1 with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.8.2 \
	&& make && make install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
