#!/bin/bash

function	compile_util_linux_pass1()
{
	package_init util-linux 0.2

	do_chroot "cd /sources/${package_tar_folder} \
	&& mkdir -pv /var/lib/hwclock \
	&& ./configure --libdir=/usr/lib \
            --runstatedir=/run \
            --disable-chfn-chsh \
            --disable-login \
            --disable-nologin \
            --disable-su \
            --disable-setpriv \
            --disable-runuser \
            --disable-pylibmount \
            --disable-static \
            --without-python \
            ADJTIME_PATH=/var/lib/hwclock/adjtime \
            --docdir=/usr/share/doc/util-linux-${package_version} \
	&& make \
	&& make install"

	package_clean
}
