#!/usr/bin/bash

function	compile_perl_pass1()
{
	package_init perl 0.6

	local	tmp_ver="${package_version%.*}"

	do_chroot "cd /sources/${package_tar_folder} \
	&& sh Configure -des \
		-Dprefix=/usr \
		-Dvendorprefix=/usr \
		-Duseshrplib \
		-Dprivlib=/usr/lib/perl5/${tmp_ver}/core_perl \
		-Darchlib=/usr/lib/perl5/${tmp_ver}/core_perl \
		-Dsitelib=/usr/lib/perl5/${tmp_ver}/site_perl \
		-Dsitearch=/usr/lib/perl5/${tmp_ver}/site_perl \
		-Dvendorlib=/usr/lib/perl5/${tmp_ver}/vendor_perl \
		-Dvendorarch=/usr/lib/perl5/${tmp_ver}/vendor_perl \
	&& make \
	&& make install"

	package_clean
}
