#!/bin/bash

function	compile_bison_pass1()
{
	package_init bison 0.2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr --docdir=/usr/share/doc/bison-${package_version} \
	&& make \
	&& make install"

	package_clean
}
