#!/bin/bash

function	create_full_fhs()
{
	do_chroot mkdir -pv /{boot,home,mnt,opt,srv}
	do_chroot mkdir -pv /etc/{opt,sysconfig}
	do_chroot mkdir -pv /lib/firmware
	do_chroot mkdir -pv /media/{floppy,cdrom}
	do_chroot mkdir -pv /usr/{,local/}{include,src}
	do_chroot mkdir -pv /usr/local/{bin,lib,sbin}
	do_chroot mkdir -pv /usr/{,local/}share/{color,dict,doc,info,locale,man}
	do_chroot mkdir -pv /usr/{,local/}share/{misc,terminfo,zoneinfo}
	do_chroot mkdir -pv /usr/{,local/}share/man/man{1..8}
	do_chroot mkdir -pv /var/{cache,local,log,mail,opt,spool}
	do_chroot mkdir -pv /var/lib/{color,misc,locate}

	do_chroot ln -sfv /run /var/run
	do_chroot ln -sfv /run/lock /var/lock

	do_chroot install -dv -m 0750 /root
	do_chroot install -dv -m 1777 /tmp /var/tmp
}
