#!/bin/bash

function	create_virtualfs()
{
	pinfo "Creating virtual file system"
	mkdir -p ${LFS}/{dev,proc,sys,run}
	# Populate /dev
	mount -v --bind /dev ${LFS}/dev || true
	mount -vt devpts devpts -o gid=5,mode=0620 ${LFS}/dev/pts || true
	mount -vt proc proc ${LFS}/proc || true
	mount -vt sysfs sysfs ${LFS}/sys || true
	mount -vt tmpfs tmpfs ${LFS}/run || true
	if [ -h ${LFS}/dev/shm ]; then
		install -v -d -m 1777 ${LFS}$(realpath /dev/shm)
	else
		mount -vt tmpfs -o nosuid,nodev tmpfs ${LFS}/dev/shm
	fi
}
