#!/usr/bin/bash

function	essential_file()
{
	# Create /etc/mtab
	rm -rf "${LFS}/etc/mtab"
	do_chroot ln -sfv /proc/self/mounts /etc/mtab
	# Create /etc/hosts

	# envsubst NEED single quote
	# shellcheck disable=SC2016
	envsubst '$LFS_HOSTNAME' > "${LFS}/etc/hosts" < "${DIR_FILE}/hosts/lfs"

	# Create /etc/passwd and
	if [ "${LFS_SYSTEMD:-0}" == "0" ]; then
		cat > "${LFS}/etc/passwd" < "${DIR_FILE}/passwd/lfs_sysvinit"
		cat > "${LFS}/etc/group" < "${DIR_FILE}/group/lfs_sysvinit"
	else
		cat > "${LFS}/etc/passwd" < "${DIR_FILE}/passwd/lfs_systemd"
		cat > "${LFS}/etc/group" < "${DIR_FILE}/group/lfs_systemd"
	fi

	# Create test user
	echo "tester:x:101:101::/home/tester:/bin/bash" >> "${LFS}/etc/passwd"
	echo "tester:x:101:" >> "${LFS}/etc/group"
	do_chroot install -o tester -d "/home/tester"

	# Create log folder
	do_chroot touch /var/log/{btmp,lastlog,faillog,wtmp}
	do_chroot chgrp -v utmp /var/log/lastlog
	do_chroot chmod -v 664 /var/log/lastlog
	do_chroot chmod -v 600 /var/log/btmp
}
