#!/usr/bin/bash

# BASH PROPRETIES
## Exit immediately if a command exits with a non-zero status
set -e
## Treat unset variables as an error when substituting
set -u
## Error in pipeline will be shown
set -o pipefail

# RUNASROOT
[ "${EUID}" != "0" ] && { echo "Error: run as root"; exit 1; }

# Config
declare -x		PATH_BASE
PATH_BASE="$(realpath "${BASH_SOURCE[0]}")"
declare -x		DIR_BASE="${PATH_BASE%/*}"

# Source config
source "${DIR_BASE}/.config"

function	init()
{
	_mkdir "${DIR_LOG}"
	_mkdir "${DIR_BAK}"
	step_setup_file
	daemon_init

	set_sbu
	get_summary
}
# Functions

init

# Main
do_lfs
do_blfs

# Create user if LFS_USER_NAME is not null, at the end because skel and other
# things are setup before
if [ "${LFS_USER_NAME:-}" != "" ]; then
	do_chroot "useradd -m -s /bin/bash ${LFS_USER_NAME}"
	do_chroot "echo '${LFS_USER_NAME}:${LFS_USER_PASS}' | chpasswd"
fi

# Testing Zone

exit ${?}
