#!/usr/bin/bash

function	lfs_01_prepare()
{
	step_id_push "LFS_PREPARE" 4
	step_do checkup
	step_do partition_lfs
	lfs_mount
	step_do update_pack_meta 1
	chown -v root:root -R "${LFS_SOURCES_DIR}"
	step_do create_minimal_fhs
	step_id_pop
}

function	lfs_02_cross_toolchain()
{
	step_id_push "LFS_CROSS_TOOLCHAIN" 5
	export MAKEFLAGS="-j1"
	step_do compile_binutils_pass1
	export MAKEFLAGS="-j${LFS_CORES}"
	step_do compile_gcc_pass1
	step_do fix_linux_headers
	export MAKEFLAGS="-j1"
	step_do compile_glibc_pass1
	export MAKEFLAGS="-j${LFS_CORES}"
	step_do compile_libstdcxx
	step_id_pop
}

function	lfs_03_temp_tool()
{
	step_id_push "LFS_TEMP_TOOL" 18
	step_do compile_m4_pass1
	step_do compile_ncurses_pass1
	step_do compile_bash_pass1
	step_do compile_coreutils_pass1
	step_do compile_diffutils_pass1
	step_do compile_file_pass1
	step_do compile_findutils_pass1
	step_do compile_gawk_pass1
	step_do compile_grep_pass1
	step_do compile_gzip_pass1
	step_do compile_make_pass1
	step_do compile_patch_pass1
	step_do compile_sed_pass1
	step_do compile_tar_pass1
	step_do compile_xz_pass1
	step_do compile_binutils_pass2
	step_do compile_gcc_pass2
	step_do backup_lfs "temp_tool"
	step_id_pop
}

function	lfs_04_chroot_additional_tool()
{
	step_id_push "LFS_CHROOT_ADDITIONAL_TOOL" 10
	step_do change_ownership
	lfs_virtualfs_enable
	step_do create_full_fhs
	step_do essential_file
	step_do compile_gettext_pass1
	step_do compile_bison_pass1
	step_do compile_perl_pass1
	step_do compile_python_pass1
	step_do compile_texinfo_pass1
	step_do compile_util_linux_pass1
	step_do clean_temp_lfs
	step_id_pop
}

function	lfs_05_basic_system_soft()
{
	local	max_step=80
	[ "${LFS_SYSTEMD:-0}" == "0" ] || max_step=79
	step_id_push "LFS_BASIC_SYSTEM_SOFT" "${max_step}"
	step_do compile_man_pages
	step_do compile_iana_etc
	step_do compile_glibc_pass2
	step_do compile_zlib
	step_do compile_bzip2
	step_do compile_xz_pass2
	step_do compile_zstd
	step_do compile_file_pass2
	step_do compile_readline
	step_do compile_m4_pass2
	step_do compile_bc
	step_do compile_flex
	step_do compile_tcl
	step_do compile_expect
	step_do compile_dejagnu
	step_do compile_pkgconf
	step_do compile_binutils_pass3
	step_do compile_gmp
	step_do compile_mpfr
	step_do compile_mpc
	step_do compile_attr
	step_do compile_acl
	step_do compile_libcap
	step_do compile_libxcrypt
	step_do compile_shadow
	step_do compile_gcc_pass3
	step_do compile_ncurses_pass2
	step_do compile_sed_pass2
	step_do compile_psmisc
	step_do compile_gettext_pass2
	step_do compile_bison_pass2
	step_do compile_grep_pass2
	step_do compile_bash_pass2
	step_do compile_libtool
	step_do compile_gdbm
	step_do compile_gperf
	step_do compile_expat
	step_do compile_inetutils
	step_do compile_less
	step_do compile_perl_pass2
	step_do compile_xml_parser
	step_do compile_intltool
	step_do compile_autoconf
	step_do compile_automake
	step_do compile_openssl
	step_do compile_kmod
	step_do compile_libelf
	step_do compile_libffi
	step_do compile_python_pass2
	step_do compile_flit_core
	step_do compile_wheel
	step_do compile_setuptools
	step_do compile_ninja
	step_do compile_meson
	step_do compile_coreutils_pass2
	step_do compile_check
	step_do compile_diffutils_pass2
	step_do compile_gawk_pass2
	step_do compile_findutils_pass2
	step_do compile_groff
	step_do compile_grub
	step_do compile_gzip_pass2
	step_do compile_iproute2
	step_do compile_kbd
	step_do compile_libpipeline
	step_do compile_make_pass2
	step_do compile_patch_pass2
	step_do compile_tar_pass2
	step_do compile_texinfo_pass2
	step_do compile_vim
	step_do compile_markupsafe
	step_do compile_jinja2
	if [ "${LFS_SYSTEMD:-0}" == "0" ]; then
		step_do compile_udev
	else
		step_do compile_systemd
		step_do compile_dbus
	fi
	step_do compile_man_db
	step_do compile_procps_ng
	step_do compile_util_linux_pass2
	step_do compile_e2fsprogs
	if [ "${LFS_SYSTEMD:-0}" == "0" ]; then
		step_do compile_sysklogd
		step_do compile_sysvinit
	fi
	if [ "${LFS_STRIP_BINARIES:-0}" != "0" ]; then
		strip_binaries
	else
		pinfo "Stripping binaries skipped"
	fi
	step_do clean_basic_soft
	step_id_pop
}

function	lfs_06_system_config_systemd()
{
	step_id_push "LFS_SYSTEM_CONFIG_SYSTEMD" 8
	step_do configure_network_systemd
	step_do configure_dns
	echo "${LFS_HOSTNAME}" > "${LFS}/etc/hostname"
	step_do configure_clock_systemd
	step_do install_fonts
	step_do configure_console_systemd
	step_do configure_locale
	step_do configure_inputrc
	step_do configure_shells
	step_id_pop
}

function	lfs_06_system_config_sysvinit()
{
	step_id_push "LFS_SYSTEM_CONFIG_SYSVINIT" 12
	step_do lfs_boot_script
	step_do configure_devices
	step_do configure_network_sysvinit
	step_do configure_dns
	echo "${LFS_HOSTNAME}" > "${LFS}/etc/hostname"
	step_do configure_sysvinit
	step_do configure_clock_sysvinit
	step_do install_fonts
	step_do configure_console_sysvinit
	step_do configure_rc_site
	step_do configure_locale
	step_do configure_inputrc
	step_do configure_shells
	step_id_pop
}

function	lfs_06_system_config()
{
	if [ "${LFS_SYSTEMD:-0}" == "0" ]; then
		lfs_06_system_config_sysvinit
	else
		lfs_06_system_config_systemd
	fi
}

function	lfs_07_make_system_bootable()
{
	step_id_push "LFS_MAKE_SYSTEM_BOOTABLE" 4
	step_do configure_fstab
	step_do compile_linux
	step_do configure_grub
	step_do finish_touch
	step_id_pop
}

function	do_lfs()
{
	step_id_push "LFS" 11
	step_do lfs_01_prepare
	step_do lfs_02_cross_toolchain
	step_do lfs_03_temp_tool
	step_do lfs_04_chroot_additional_tool
	step_do lfs_05_basic_system_soft
	step_do backup_lfs "base_system"
	step_do lfs_06_system_config
	step_do backup_lfs "configured"
	step_do lfs_07_make_system_bootable
	step_do backup_lfs "bootable"
	step_do save_log
	step_id_pop
}
