#!/bin/bash

function	create_minimal_fhs()
{
	pinfo "Create directory layout"
	mkdir -pv ${LFS}/{etc,var,tools} ${LFS}/usr/{bin,lib,sbin}
	for i in bin lib sbin; do
		[ -e ${LFS}/${i} ] && rm -rf ${LFS}/${i}
		ln -sv usr/${i} ${LFS}/
	done
	case ${LFS_ARCH} in
		x86_64)
			[ -e ${LFS}/lib64 ] && rm -rf ${LFS}/lib64
			ln -sv lib ${LFS}/lib64
		;;
	esac
}
