#!/usr/bin/bash

function	compile_libstdcxx()
{
	package_init gcc 0.2

	# Exported variable
	# shellcheck disable=SC2154
	take "${dst_folder}/build"
	# Exported variable
	# shellcheck disable=SC2154
	../libstdc++-v3/configure \
		--host="${LFS_TGT}" \
		--build="$(../config.guess)" \
		--prefix=/usr \
		--disable-multilib \
		--disable-nls \
		--disable-libstdcxx-pch \
		--with-gxx-include-dir="/tools/${LFS_TGT}/include/c++/${package_version}"
	make
	make DESTDIR="${LFS}" install
	rm -rf "${LFS}/usr/lib/lib"{stdc++{,exp,fs},supc++}.la
	_popd

	package_clean
}
