#!/bin/bash

function	compile_binutils_pass1()
{
	package_init binutils "" "" 1

	take "${dst_folder}/build"
	start=`date +%s`
	../configure --prefix=${LFS}/tools \
		--with-sysroot=${LFS} \
		--target=${LFS_TGT} \
		--disable-nls \
		--enable-gprofng=no \
		--disable-werror \
		--enable-default-hash-style=gnu
	make && make install
	end=`date +%s`
	local	sbu=$((end - start))
	set_sbu "${sbu}"
	_popd

	package_clean
}
