#!/bin/bash

function	compile_glibc_pass1()
{
	package_init glibc 1.5

	_pushd ${dst_folder}
	# TO FIX, Sometimes make the script fail, with too many symbolic links
	# at the `make DESTDIR=${LFS} install` step
	# case ${LFS_ARCH} in
	# 	i?86)
	# 		_ln -s ld-linux.so.2 ${LFS}/lib/ld-lsb.so.3
	# 	;;
	# 	x86_64)
	# 		_ln -s ../lib/ld-linux-x86-64.so.2 ${LFS}/lib64/ld-linux-x86-64.so.2
	# 		_ln -s ../lib/ld-linux-x86-64.so.2 ${LFS}/lib64/ld-lsb-x86-64.so.3
	# 	;;
	# esac
	patch -Np1 -i "$(package_get_src_file "patch_glibc-fhs")"
	take ${dst_folder}/build
	echo "rootsbindir=/usr/sbin" > configparms
	../configure \
		--prefix=/usr \
		--host=${LFS_TGT} \
		--build=$(../scripts/config.guess) \
		--enable-kernel=4.19 \
		--with-headers=${LFS}/usr/include \
		--disable-nscd \
		libc_cv_slibdir=/usr/lib
	make
	make DESTDIR=${LFS} install
	sed '/RTLDLIST=/s@/usr@@g' -i ${LFS}/usr/bin/ldd
	_popd 2

	# test glibc
	echo 'int main(){}' | ${LFS_TGT}-gcc -xc -
	readelf -l a.out | grep ld-linux
	_rm a.out

	package_clean
}
