#!/usr/bin/bash

function	compile_findutils_pass1()
{
	package_init findutils 0.1

	_pushd "${dst_folder}"
	./configure --prefix=/usr \
		--localstatedir=/var/lib/locate \
		--host="${LFS_TGT}" \
		--build="$(build-aux/config.guess)"
	make
	make DESTDIR="${LFS}" install
	_popd

	package_clean
}

