#!/bin/bash

function	compile_make_pass1()
{
	package_init make 0

	_pushd ${dst_folder}
	./configure --prefix=/usr \
		--without-guile \
		--host=${LFS_TGT} \
		--build=$(build-aux/config.guess)
	make
	make DESTDIR=${LFS} install
	_popd

	package_clean
}
