#!/bin/bash

function	compile_gcc_pass2()
{
	package_init gcc 4.4 2 1

	_pushd ${dst_folder}
	_tar -xf ../${PACKAGE_FILE["mpfr"]}
	_tar -xf ../${PACKAGE_FILE["gmp"]}
	_tar -xf ../${PACKAGE_FILE["mpc"]}
	_rm mpfr; _mv mpfr-* mpfr
	_rm gmp; _mv gmp-* gmp
	_rm mpc; _mv mpc-* mpc
	case ${LFS_ARCH} in
		x86_64)
			sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
		;;
	esac
	sed '/thread_header =/s/@.*@/gthr-posix.h/' \
		-i libgcc/Makefile.in libstdc++-v3/include/Makefile.in
	take ${dst_folder}/build
	../configure \
		--build=$(../config.guess) \
		--host=${LFS_TGT} \
		--target=${LFS_TGT} \
		LDFLAGS_FOR_TARGET=-L${PWD}/${LFS_TGT}/libgcc \
		--prefix=/usr \
		--with-build-sysroot=${LFS} \
		--enable-default-pie \
		--enable-default-ssp \
		--disable-nls \
		--disable-multilib \
		--disable-libatomic \
		--disable-libgomp \
		--disable-libquadmath \
		--disable-libsanitizer \
		--disable-libssp \
		--disable-libvtv \
		--enable-languages=c,c++
	make
	make DESTDIR=${LFS} install
	[ ! -e ${LFS}/usr/bin/cc ] && \
		_ln -s gcc ${LFS}/usr/bin/cc
	_popd -2

	package_clean
}
