#!/usr/bin/bash

function	compile_gzip_pass1()
{
	package_init gzip 0.1

	_pushd "${dst_folder}"
	./configure --prefix=/usr \
		--host="${LFS_TGT}"
	make
	make DESTDIR="${LFS}" install
	_popd

	package_clean
}
