#!/usr/bin/bash

function	compile_bash_pass1()
{
	package_init bash 0.2

	_pushd "${dst_folder}"
	./configure --prefix=/usr \
		--build="$(sh support/config.guess)" \
		--host="${LFS_TGT}" \
		--without-bash-malloc
	make
	make DESTDIR="${LFS}" install
	[ ! -e "${LFS}/bin/sh" ] && _ln -sf bash "${LFS}/bin/sh"
	_popd

	package_clean
}
