#!/usr/bin/bash

function	compile_patch_pass1()
{
	package_init patch 0.1

	_pushd "${dst_folder}"
	./configure --prefix=/usr \
		--host="${LFS_TGT}" \
		--build="$(build-aux/config.guess)"
	make
	make DESTDIR="${LFS}" install
	_popd

	package_clean
}
