#!/usr/bin/bash

function	compile_file_pass1()
{
	package_init file 0.1

	_pushd "${dst_folder}"
	take "${dst_folder}/build"
	../configure --disable-bzlib \
		--disable-libseccomp \
		--disable-xzlib \
		--disable-zlib
	make
	_popd
	./configure --prefix=/usr --host="${LFS_TGT}" --build="$(./config.guess)"
	make FILE_COMPILE="${dst_folder}/build/src/file"
	make DESTDIR="${LFS}" install
	_rm "${LFS}/usr/lib/libmagic.la"
	_popd

	package_clean
}
