#!/bin/bash

function	compile_binutils_pass2()
{
	package_init binutils 0.5 2 1

	take ${dst_folder}/build
	sed '6009s/$add_dir//' -i ../ltmain.sh
	../configure \
		--prefix=/usr \
		--build=$(../config.guess) \
		--host=${LFS_TGT} \
		--disable-nls \
		--enable-shared \
		--enable-gprofng=no \
		--disable-werror \
		--enable-64-bit-bfd \
		--enable-default-hash-style=gnu
	make
	make DESTDIR=${LFS} install
	rm -rf ${LFS}/usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes,sframe}.{a,la}
	_popd

	package_clean
}
