#!/usr/bin/bash

function	compile_coreutils_pass1()
{
	package_init coreutils 0.3

	_pushd "${dst_folder}"
	./configure --prefix=/usr \
		--host="${LFS_TGT}" \
		--build="$(build-aux/config.guess)" \
		--enable-install-program=hostname \
		--enable-no-install-program=kill,uptime
	make
	make DESTDIR="${LFS}" install
	_mv "${LFS}/usr/bin/chroot" "${LFS}/usr/sbin"
	_mkdir "${LFS}/usr/share/man/man8"
	_mv "${LFS}/usr/share/man/man1/chroot.1" "${LFS}/usr/share/man/man8/chroot.8"
	sed -i 's/"1"/"8"/' "${LFS}/usr/share/man/man8/chroot.8"
	_popd

	package_clean
}
