#!/bin/bash

function	compile_gawk_pass1()
{
	package_init gawk 0.1

	_pushd ${dst_folder}
	sed -i 's/extras//' Makefile.in
	./configure --prefix=/usr \
		--host=${LFS_TGT} \
		--build=$(build-aux/config.guess)
	make
	make DESTDIR=${LFS} install
	_popd

	package_clean
}
