#!/usr/bin/bash

function	configure_skel()
{
	_mkdir "${LFS}/etc/skel"
	_mkdir "${LFS}/etc/skel/.vim"

	cat_default_file "${LFS}/etc/skel/.bashrc" < "${DIR_FILE}/skel/bashrc"
	cat_default_file "${LFS}/etc/skel/.vim/vimrc" '"' < "${DIR_FILE}/skel/vimrc"
	# Duplicate, file already setup in compile_vim
	cat_default_file "${LFS}/etc/vimrc" '"' < "${DIR_FILE}/vimrc"
	cat_default_file "${LFS}/etc/skel/.profile" < "${DIR_FILE}/skel/profile"
}
