#!/usr/bin/bash

function	blfs_01_after_lfs()
{
	step_id_push "BLFS_AFTER_LFS" 5

	step_do configure_group_user
	step_do configure_skel
	step_do configure_profile
	step_do configure_issue
	step_do create_user
	step_id_pop
}

function	blfs_02_security()
{
	step_id_push "BLFS_SECURITY" 1000
	step_do dot_mngr_install_blfs 1_make-ca
	step_do dot_mngr_install_blfs 1_cracklib
	step_do dot_mngr_install_blfs 1_cryptsetup
	step_do dot_mngr_install_blfs 1_cyrus-sasl
	step_do dot_mngr_install_blfs 1_gnupg
	step_do dot_mngr_install_blfs 1_gpgme
	step_do dot_mngr_install_blfs 1_iptables
	step_do dot_mngr_install_blfs 1_linux-pam
	step_do dot_mngr_install_blfs 1_sudo

	exit 131
	step_id_pop
}

function	do_blfs()
{
	step_id_push "BLFS" 1
	step_do blfs_01_after_lfs
	step_do blfs_02_security
	step_do backup_lfs "blfs"
	step_id_pop
}
