#!/bin/bash

function	configure_clock()
{
	chroot_line "# Begin default /etc/sysconfig/clock" /etc/sysconfig/clock 1
	chroot_line "" /etc/sysconfig/clock
	chroot_line "UTC=${LFS_CLOCK_UTC}" /etc/sysconfig/clock
	chroot_line "" /etc/sysconfig/clock
	chroot_line "# Set this to any options you might need to give to hwclock," /etc/sysconfig/clock
	chroot_line "# such as machine hardware clock type for Alphas." /etc/sysconfig/clock
	chroot_line "CLOCKPARAMS=${LFS_CLOCKPARAMS}" /etc/sysconfig/clock
	chroot_line "" /etc/sysconfig/clock
	do_chroot cp -v --remove-destination /usr/share/zoneinfo/${LFS_TZ} /etc/localtime
}
