#!/bin/bash

function	configure_dns()
{
	local	dns_file="/etc/resolv.conf"

	chroot_line "# Begin default /etc/resolv.conf" "${dns_file}" 1
	chroot_line "" "${dns_file}"
	chroot_line "nameserver ${LFS_DNS_PRIMARY}" "${dns_file}"
	if [ "${LFS_DNS_SECONDARY:-}" != "" ]; then
		chroot_line "nameserver ${LFS_DNS_SECONDARY}" "${dns_file}"
	fi
	chroot_line "" "${dns_file}"
	chroot_line "# End default /etc/resolv.conf" "${dns_file}"
}
