#!/bin/bash

function	compile_libstdcxx()
{
	local	dst_dir="${LFS_SOURCES_DIR}/gcc-13.2.0"
	local	sbu="0.2"

	pinfo "Building Libstdc++ with SBU ${sbu} ($(get_sbu ${sbu})s)"
	rm -rf ${dst_dir}/build
	take ${dst_dir}/build
	../libstdc++-v3/configure \
		--host=${LFS_TGT} \
		--build=$(../config.guess) \
		--prefix=/usr \
		--disable-multilib \
		--disable-nls \
		--disable-libstdcxx-pch \
		--with-gxx-include-dir=/tools/${LFS_TGT}/include/c++/13.2.0
	make
	make DESTDIR=${LFS} install
	rm -v ${LFS}/usr/lib/lib{stdc++{,exp,fs},supc++}.la
	popd
	ppass "Builded Libstdc++"
}
