#!/bin/bash

function	compile_binutils_pass1()
{
	local	dst_dir="${LFS_SOURCES_DIR}/binutils-2.42"
	local	package="binutils"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} pass 1 and getting SBU"
	[ -e ${dst_dir} ] && rm -rf ${dst_dir}
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	take ${dst_dir}/build
	start=`date +%s.%N`
	../configure --prefix=${LFS}/tools \
		--with-sysroot=${LFS} \
		--target=${LFS_TGT} \
		--disable-nls \
		--enable-gprofng=no \
		--disable-werror \
		--enable-default-hash-style=gnu
	make && make install
	end=`date +%s.%N`
	local	sbu=$(printf "%.6f\n" $(echo "${end} - ${start}" | bc -l))
	set_sbu "${sbu}"
	popd
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
