#!/bin/bash

function	clean_basic_soft()
{
	pinfo "Cleaning basic system soft"
	rm -rf /tmp/*
	find /usr/lib /usr/libexec -name \*.la -delete
	find /usr -depth -name $(uname -m)-lfs-linux-gnu\* | xargs rm -rf
	userdel -r tester
}
