#!/bin/bash

function	compile_gperf()
{
	local	dst_dir="gperf-3.1"
	local	sbu="0.05"
	local	package="gperf"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU less than 0.1 ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.1 \
	&& make \
	&& make -j1 check \
	&& make install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
