#!/bin/bash

function	compile_sysklogd()
{
	local	dst_dir="sysklogd-1.5.1"
	local	sbu="0.05"
	local	package="sysklogd"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU less than 0.1 ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& sed -i '/Error loading kernel symbols/{n;n;d}' ksym_mod.c \
	&& sed -i 's/union wait/int/' syslogd.c \
	&& make \
	&& make BINDIR=/sbin install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	pinfo "Configuring ${PACKAGE_FILE[${package}]::-7}"
	chroot_line "# Begin /etc/syslog.conf" /etc/syslog.conf 1
	chroot_line "" /etc/syslog.conf
	chroot_line "auth,authpriv.* -/var/log/auth.log" /etc/syslog.conf
	chroot_line "*.*;auth,authpriv.none -/var/log/sys.log" /etc/syslog.conf
	chroot_line "daemon.* -/var/log/daemon.log" /etc/syslog.conf
	chroot_line "kern.* -/var/log/kern.log" /etc/syslog.conf
	chroot_line "mail.* -/var/log/mail.log" /etc/syslog.conf
	chroot_line "user.* -/var/log/user.log" /etc/syslog.conf
	chroot_line "*.emerg *" /etc/syslog.conf
	chroot_line "" /etc/syslog.conf
	chroot_line "# End /etc/syslog.conf" /etc/syslog.conf
	ppass "Configured ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
