#!/bin/bash

function	compile_util_linux_pass2()
{
	local	dst_dir="util-linux-2.39.3"
	local	sbu="0.5"
	local	package="util-linux"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& sed -i '/test_mkfds/s/^/#/' tests/helpers/Makemodule.am \
	&& ./configure --bindir=/usr/bin \
		--libdir=/usr/lib \
		--runstatedir=/run \
		--sbindir=/usr/sbin \
		--disable-chfn-chsh \
		--disable-login \
		--disable-nologin \
		--disable-su \
		--disable-setpriv \
		--disable-runuser \
		--disable-pylibmount \
		--disable-static \
		--without-python \
		--without-systemd \
		--without-systemdsystemunitdir \
		ADJTIME_PATH=/var/lib/hwclock/adjtime \
		--docdir=/usr/share/doc/util-linux-2.39.3 \
	&& make \
	&& chown -R tester . \
	&& su tester -c \"make -k check\" \
	&& make install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
