#!/bin/bash

function	compile_libelf()
{
	local	dst_dir="elfutils-0.191"
	local	sbu="0.3"
	local	package="elfutils"

	pinfo "Building libelf from ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr \
		--disable-debuginfod \
		--enable-libdebuginfod=dummy \
	&& make \
	&& make check \
	&& make -C libelf install \
	&& install -vm644 config/libelf.pc /usr/lib/pkgconfig \
	&& rm /usr/lib/libelf.a"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
