#!/bin/bash

function	compile_check()
{
	local	dst_dir="check-0.15.2"
	local	sbu="1.6"
	local	package="check"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr --disable-static \
	&& make \
	&& make check \
	&& make docdir=/usr/share/doc/check-0.15.2 install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
