#!/bin/bash

function	compile_inetutils()
{
	local	dst_dir="inetutils-2.5"
	local	sbu="0.2"
	local	package="inetutils"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr \
		--bindir=/usr/bin \
		--localstatedir=/var \
		--disable-logger \
		--disable-whois \
		--disable-rcp \
		--disable-rexec \
		--disable-rlogin \
		--disable-rsh \
		--disable-servers \
	&& make \
	&& make check \
	&& make install \
	&& mv -v /usr/{,s}bin/ifconfig"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
