#!/bin/bash

function	compile_shadow()
{
	local	dst_dir="shadow-4.15.0-rc2"
	local	sbu="0.1"
	local	package="shadow"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& sed -i 's/groups\$(EXEEXT) //' src/Makefile.in \
	&& find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \; \
	&& find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \; \
	&& find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \; \
	&& sed -e 's:#ENCRYPT_METHOD DES:ENCRYPT_METHOD YESCRYPT:' \
		-e 's:/var/spool/mail:/var/mail:' \
		-e '/PATH=/{s@/sbin:@@;s@/bin:@@}' \
		-i etc/login.defs \
	&& touch /usr/bin/passwd \
	&& ./configure --sysconfdir=/etc \
		--disable-static \
		--with-{b,yes}crypt \
		--without-libbsd \
		--with-group-name-max-length=32 \
	&& make \
	&& make exec_prefix=/usr install \
	&& make -C man install-man"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	pinfo "Configuring ${PACKAGE_FILE[${package}]::-7}"
	do_chroot "pwconv \
	&& grpconv \
	&& mkdir -p /etc/default \
	&& useradd -D --gid 999 \
	&& sed -i '/MAIL/s/yes/no/' /etc/default/useradd \
	&& echo 'root:1234' | chpasswd"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
