#!/bin/bash

function	compile_xml_parser()
{
	local	dst_dir="XML-Parser-2.47"
	local	sbu="0.05"
	local	package="xml-parser"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU less than 0.1 ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& perl Makefile.PL \
	&& make \
	&& make test \
	&& make install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
