#!/bin/bash

function	compile_gmp()
{
	local	dst_dir="gmp-6.3.0"
	local	sbu="0.3"
	local	package="gmp"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr \
		--enable-cxx \
		--disable-static \
		--docdir=/usr/share/doc/gmp-6.3.0 \
	&& make \
	&& make html \
	&& make check 2>&1 | tee gmp-check-log \
	&& make install \
	&& make install-html \
	&& awk '/# PASS:/{total+=\$3} ; END{print total}' gmp-check-log"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
