#!/bin/bash

function	compile_grub()
{
	local	dst_dir="grub-2.12"
	local	sbu="0.3"
	local	package="grub"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& unset {C,CPP,CXX,LD}FLAGS \
	&& echo depends bli part_gpt > grub-core/extra_deps.lst \
	&& ./configure --prefix=/usr \
		--sysconfdir=/etc \
		--disable-efiemu \
		--disable-werror \
	&& make \
	&& make install \
	&& mv -v /etc/bash_completion.d/grub /usr/share/bash-completion/completions"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}


