#!/bin/bash

function	compile_ncurses_pass2()
{
	local	dst_dir="ncurses-6.4-20230520"
	local	sbu="0.2"
	local	package="ncurses"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} pass 2 with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr \
		--mandir=/usr/share/man \
		--with-shared \
		--without-debug \
		--without-normal \
		--with-cxx-shared \
		--enable-pc-files \
		--enable-widec \
		--with-pkg-config-libdir=/usr/lib/pkgconfig \
	&& make \
	&& make DESTDIR=\$PWD/dest install \
	&& install -vm755 dest/usr/lib/libncursesw.so.6.4 /usr/lib \
	&& rm -v  dest/usr/lib/libncursesw.so.6.4 \
	&& sed -e 's/^#if.*XOPEN.*$/#if 1/' -i dest/usr/include/curses.h \
	&& cp -av dest/* / \
	&& for lib in ncurses form panel menu ; do
		ln -sfv lib\${lib}w.so /usr/lib/lib\${lib}.so \
		&& ln -sfv \${lib}w.pc /usr/lib/pkgconfig/\${lib}.pc; \
	done \
	&& ln -sfv libncursesw.so /usr/lib/libcurses.so \
	&& cp -v -R doc -T /usr/share/doc/ncurses-6.4-20230520 \
	&& make distclean \
	&& ./configure --prefix=/usr \
		--with-shared \
		--without-normal \
		--without-debug \
		--without-cxx-binding \
		--with-abi-version=5 \
	&& make sources libs \
	&& cp -av lib/lib*.so.5* /usr/lib"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
