#!/bin/bash

function	compile_procps_ng()
{
	local	dst_dir="procps-ng-4.0.4"
	local	sbu="0.1"
	local	package="procps-ng"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr \
		--docdir=/usr/share/doc/procps-ng-4.0.4 \
		--disable-static \
		--disable-kill \
	&& make \
	&& make -k check || true \
	&& make install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
