#!/bin/bash

function	compile_iproute2()
{
	local	dst_dir="iproute2-6.7.0"
	local	sbu="0.1"
	local	package="iproute2"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& sed -i /ARPD/d Makefile \
	&& rm -fv man/man8/arpd.8 \
	&& make NETNS_RUN_DIR=/run/netns \
	&& make SBINDIR=/usr/sbin install \
	&& mkdir -pv /usr/share/doc/iproute2-6.7.0 \
	&& cp -v COPYING README* /usr/share/doc/iproute2-6.7.0"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
