#!/bin/bash

function	compile_binutils_pass3()
{
	local	dst_dir="binutils-2.42"
	local	sbu="2.2"
	local	package="binutils"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} pass 3 with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "mkdir -vp /sources/${dst_dir}/build && cd /sources/${dst_dir}/build \
	&& ../configure --prefix=/usr \
		--sysconfdir=/etc \
		--enable-gold \
		--enable-ld=default \
		--enable-plugins \
		--enable-shared \
		--disable-werror \
		--enable-64-bit-bfd \
		--with-system-zlib \
		--enable-default-hash-style=gnu \
	&& make tooldir=/usr \
	&& make -k check || true \
	&& make tooldir=/usr install \
	&& rm -fv /usr/lib/lib{bfd,ctf,ctf-nobfd,gprofng,opcodes,sframe}.a"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
