#!/bin/bash

function	compile_bison()
{
	local	dst_dir="${LFS_SOURCES_DIR}/bison-3.8.2"
	local	sbu="0.2"
	local	package="bison"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/bison-3.8.2 \
	&& ./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.8.2 \
	&& make && make install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
