#!/bin/bash

function	compile_python()
{
	local	dst_dir="${LFS_SOURCES_DIR}/Python-3.12.2"
	local	sbu="0.5"
	local	package="python"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/Python-3.12.2 \
	&&./configure --prefix=/usr   \
		--enable-shared \
		--without-ensurepip \
	&& make && make install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
