#!/bin/bash

function	compile_gettext_pass1()
{
	local	dst_dir="gettext-0.22.5"
	local	sbu="1.1"
	local	package="gettext"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} pass 1 with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --disable-shared \
	&& make \
	&& cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
