#!/bin/bash

function	compile_perl()
{
	local	dst_dir="${LFS_SOURCES_DIR}/perl-5.38.2"
	local	sbu="0.6"
	local	package="perl"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/perl-5.38.2 \
	&& sh Configure -des \
		-Dprefix=/usr \
		-Dvendorprefix=/usr \
		-Duseshrplib \
		-Dprivlib=/usr/lib/perl5/5.38/core_perl \
		-Darchlib=/usr/lib/perl5/5.38/core_perl \
		-Dsitelib=/usr/lib/perl5/5.38/site_perl \
		-Dsitearch=/usr/lib/perl5/5.38/site_perl \
		-Dvendorlib=/usr/lib/perl5/5.38/vendor_perl \
		-Dvendorarch=/usr/lib/perl5/5.38/vendor_perl \
	&& make && make install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
