#!/bin/bash

function	compile_texinfo()
{
	local	dst_dir="${LFS_SOURCES_DIR}/texinfo-7.1"
	local	sbu="0.2"
	local	package="texinfo"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/texinfo-7.1 \
	&& ./configure --prefix=/usr \
	&& make && make install"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
