#!/usr/bin/bash

function	daemon_print_status()
{
	local	beg="${CUR_SAV}${CSI}${S_LINES};1H${CLR_LINE}"
	local	end

	end="${POS_DATE}${RED}${BOL}$(date +'%T')${RST}${RST_BOL}${CUR_RES}"
	echo -ne "${beg}$(cat "${DAEMON_OUT}")${dot}${end}" > "${tty}"
}

function	daemon_sigint()
{
	exit ${?}
}

function	daemon_status()
{
	declare -g	tty="${1}"
	declare -g	index_dot=0
	declare -g	dot="."

	set +x
	trap daemon_sigint SIGINT
	trap get_screen_size WINCH

	while true; do
		daemon_print_status
		sleep "${DAEMON_REFRESH_RATE}"
		((index_dot++)) || true
		if [ "${index_dot}" -gt 10 ]; then
			case ${dot} in
				".")	dot=".."	;;
				"..")	dot="..."	;;
				"...")	dot="."		;;
				*) 		dot="."		;;
			esac
			index_dot=0
		fi
	done
}

function	get_screen_size()
{
	S_LINES="$(cut -d' ' -f1 < "${SCREEN_SIZE}")"
	S_COLUMNS="$(cut -d' ' -f2 < "${SCREEN_SIZE}")"
	export S_LINES
	export S_COLUMNS
	POS_DATE="${CSI}${S_LINES};$((S_COLUMNS - 7))H"
}

function	update_screen_size()
{
	stty size > "${SCREEN_SIZE}"
}

function	set_scrolling_region()
{
	update_screen_size
	get_screen_size
	echo -ne "${CLR_SCREEN}${CSI};$((S_LINES - 1))r"
}

function	daemon_init()
{
	echo -ne "${VID_ENA}${CUR_DIS}"
	set_scrolling_region

	dset "${BOL}${GRE}INIT${RST}${RST_BOL}"

	daemon_status "$(tty)" &
	export DAEMON_PID="${!}"

	trap set_scrolling_region WINCH

	ppass "Daemon launched with PID: ${DAEMON_PID}"
}

function	daemon_kill()
{
	echo -ne "${CSI}r${CUR_ENA}${VID_DIS}"
	kill -s SIGINT "${DAEMON_PID}" &>/dev/null || true
	wait "${DAEMON_PID}" || true
}

function	dset()
{ echo -n "${1}" > "${DAEMON_OUT}"; }
