#!/usr/bin/bash

function	install_dot_mngr()
{
	if [ ! -d "dot_mngr" ]; then
		sudo -u "${WHOAMI}" bash -c "git clone https://github.com/Pixailz/dot_mngr"
	fi
	if [ ! -d "/root/.config/dot_mngr" ]; then
		mkdir -p /root/.config
		if [ ! -d "${WHOAMI_HOME}/.config/dot_mngr" ]; then
			sudo -u "${WHOAMI}" mkdir -p "${WHOAMI_HOME}/.config/dot_mngr"
		fi
		ln -s "${WHOAMI_HOME}/.config/dot_mngr" /root/.config/dot_mngr
	fi
	if [ "$(python3 -m pip list | grep dot-mngr | wc -l)" != "1" ]; then
		sudo -u "${WHOAMI}" pip install -e ./dot_mngr
		pip install -e ./dot_mngr
	fi
	cat <<-EOF > "${WHOAMI_HOME}/.config/dot_mngr/sources.list"
		lfs_repo https://github.com/Pixailz/dot_mngr_repo lfs
	EOF
}

# function	activate_dot_mngr()
# {
# 	. ./venv/bin/activate || true
# }

# function	deactivate_dot_mngr()
# {
# 	deactivate
# }

function	dot_mngr_exec()
{
	python3 -m dot_mngr ${@}
}

function	dot_mngr_install()
{
	dot_mngr_exec \
		--target-triplet "${LFS_TGT}" \
		--use-prefix "${LFS}" \
			install ${@} \
				--extract-folder "${LFS}/sources"
}

function	dot_mngr_info()
{
	dot_mngr_exec \
		--target-triplet "${LFS_TGT}" \
		--use-prefix "${LFS}" \
			info
}
