#!/usr/bin/bash

function	install_dot_mngr()
{
	if [ ! -d "dot_mngr" ]; then
		sudo -u "${WHOAMI}" bash -c "git clone https://github.com/Pixailz/dot_mngr"
	fi
	if [ ! -d "venv" ]; then
		sudo -u "${WHOAMI}" bash -c "python3 -m venv ./venv"
	fi
	activate_dot_mngr
	if [ "$(type -t dot_mngr)" != "file" ]; then
		sudo -u "${WHOAMI}" pip install -e ./dot_mngr
		pip install -e ./dot_mngr
	fi

	if [ ! -d "/root/.config/dot_mngr" ]; then
		mkdir -p /root/.config
		ln -s "${WHOAMI_HOME}/.config/dot_mngr" /root/.config/dot_mngr
	fi

	cat <<-EOF > "${WHOAMI_HOME}/.config/dot_mngr/sources.list"
		lfs_repo https://github.com/Pixailz/dot_mngr_repo lfs
	EOF
}

function	activate_dot_mngr()
{
	. ./venv/bin/activate || true
}

function	deactivate_dot_mngr()
{
	deactivate
}

function	dot_mngr_install()
{
	dot_mngr \
		--target-triplet "${LFS_TGT}" \
		--use-prefix "${LFS}" \
		install ${@}
}
