#!/usr/bin/bash

function	install_dot_mngr()
{
	if [ ! -d "dot_mngr" ]; then
		sudo -u "${WHOAMI}" bash -c "git clone https://github.com/Pixailz/dot_mngr"
	fi
	if [ ! -d "/root/.config/dot_mngr" ]; then
		mkdir -p /root/.config
		if [ ! -d "${WHOAMI_HOME}/.config/dot_mngr" ]; then
			sudo -u "${WHOAMI}" mkdir -p "${WHOAMI_HOME}/.config/dot_mngr"
		fi
		ln -s "${WHOAMI_HOME}/.config/dot_mngr" /root/.config/dot_mngr
	fi
	if [ "$(python3 -m pip list | grep dot_mngr | wc -l)" != "1" ]; then
		sudo -u "${WHOAMI}" pip install --break-system-packages -e ./dot_mngr
		pip install --break-system-packages -e ./dot_mngr
	fi
	cat <<-EOF > "${WHOAMI_HOME}/.config/dot_mngr/sources.list"
		lfs https://github.com/Pixailz/dot_mngr_repo lfs
		blfs https://github.com/Pixailz/dot_mngr_repo blfs
		main https://github.com/Pixailz/dot_mngr_repo main
	EOF

	# Exported variables to dot_mngr
	export DISTRO_CODENAME="${LFS_DISTRO_CODENAME}"
	export VMLINUZ="${LFS_VMLINUZ}"
	export VMLINUZ_SUFFIX="${LFS_VMLINUZ_SUFFIX}"
	export DO_CHECK="${LFS_DO_CHECK}"
	export TARGET_TRIPLET="${LFS_TGT}"
	export ROOT_PATH="${LFS}"
	export EXTRACT_FOLDER="${LFS_SOURCES_DIR}"
	export CLEAN_LOG="${LOG_FILE_KEEP}"
}

# function	activate_dot_mngr()
# {
# 	. ./venv/bin/activate || true
# }

# function	deactivate_dot_mngr()
# {
# 	deactivate
# }

function	dot_mngr_exec()
{
	python3 -m dot_mngr ${@}
}

function	dot_mngr_install()
{
	dot_mngr_exec install ${@}
}

function	dot_mngr_info()
{
	dot_mngr_exec info ${@}
}

function	dot_mngr_install_blfs()
{
	local	key="${1#[0-9]_*}"

	for k in "${!BLFS_TODO[@]}"; do
		if [ "${k}" == "${key}" ] && [ "${BLFS_TODO[${key}]}" == "0" ]; then
			pwarm "Skipping ${key}..."
			return 0
		fi
	done
	dot_mngr_install ${@}
}
