#!/usr/bin/bash

function	ptitle()
{
	local	est_sbu
	est_sbu="$(calc_sbu "${1}" "${2}")"
	local	hdr="${HDR_TITLE}"
	local	est_sbu_col="${GRE}"

	if [ "${est_sbu}" == "0" ]; then
		est_sbu="No Compilation"
		est_sbu_col="${RED}"
	else
		est_sbu="SBU~:${est_sbu} ($(get_sbu "${est_sbu}"))"
	fi
	est_sbu="${est_sbu_col}${est_sbu}${RST}"

	_printf "${hdr}" "${*:3} ${est_sbu}"
}

function	get_index()
{
	local	ind_beg="${BLU}${BOL}"
	local	ind_end="${RST}${RST_BOL}"
	local	ind="${ind_beg}${2}${ind_end}"

	ptitle "${1}" "${4:-/NOT/FOUND/}" "${ind} $(printf "%-${LOG_TITLE_SIZE}s" "${3}")"
}

function	get_summary_lfs()
{
	get_index "${DIR_LFS}/**/*" "1  " "LFS (${GRE}${LFS_DISTRO_VERSION}${RST})"
	log_lvl_push 1
	get_index "${DIR_LFS}/01_prepare/*" "1.1" "Prepare"
	get_index "${DIR_LFS}/02_cross_toolchain/*" "1.2" "Cross Toolchain"
	get_index "${DIR_LFS}/03_temp_tool/*" "1.3" "Temp Tool"
	get_index "${DIR_LFS}/04_chroot_additional_tool/*" "1.4" "Chroot Additional Tool"
	get_index "${DIR_LFS}/05_basic_system_soft/*" "1.5" "Basic System Soft"
	get_index "${DIR_LFS}/06_system_config/*" "1.6" "System Config"
	get_index "${DIR_LFS}/07_make_system_bootable/*" "1.7" "Make System Bootable"
	log_lvl_pop
}

function	get_summary()
{
	dset "${BOL}${CYA}Summary${RST}${RST_BOL}"
	get_summary_lfs
}
