#!/usr/bin/bash

function	print_retv()
{
	local	str="Program ended"
	local	pfunc=""

	if [ "${CTRL_C_PRESSED:-0}" == "1" ]; then
		pfunc="pwarn"
		str+=", interrupted by user"
		str+=", with return value (${YEL}${LAST_RETURN_CODE}${RST})"
	elif [ "${LAST_RETURN_CODE}" == "0" ]; then
		pfunc="ppass"
		str+=" successfully"
		str+=", with return value (${GRE}${LAST_RETURN_CODE}${RST})"
	else
		pfunc="pfail"
		str+=" with error code: ${RED}${LAST_RETURN_CODE}${RST}"
	fi

	${pfunc} "${str}"
	press_akey "Press a key at anytime to exit"
}

function	trap_exit()
{
	LAST_RETURN_CODE=${LAST_RETURN_CODE:-${?}}

	trap "trap_exit 1" SIGINT

	[ "${1:-}" == "" ] && print_retv

	daemon_kill

	rm -rf /tmp/.{screen_size,daemon_out,daemon_wait}.*

	unset "${!LFS_@} ${!DIR_@} ${!LOG_@} ${!SBU_@} ${!GET_PACK_@} ${!PACKAGE_@} \
		${!CURRENT_PACKAGE_@} ${!DAEMON_@} ${!S_@} \
		PATH_BASE LC_ALL CONFIG_SITE MAKEFLAGS CTRL_C_PRESSED"
	# echo exit "${LAST_RETURN_CODE}"

	exit "${LAST_RETURN_CODE}"
}

function	trap_sigint()
{
	LAST_RETURN_CODE="${?}"
	CTRL_C_PRESSED=1
	unset -n last_step step
	echo
	# echo sigint "${LAST_RETURN_CODE}"
	exit "${LAST_RETURN_CODE}"
}

trap trap_sigint SIGINT
trap trap_exit EXIT
