#!/bin/bash

function	compile_make_pass1()
{
	local	dst_dir="${LFS_SOURCES_DIR}/make-4.4.1"
	local	sbu="0.05"
	local	package="make"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} pass 1 with SBU less than 0.1 ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	pushd ${dst_dir}
	./configure --prefix=/usr \
		--without-guile \
		--host=${LFS_TGT} \
		--build=$(build-aux/config.guess)
	make
	make DESTDIR=${LFS} install
	popd
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
