#!/bin/bash

function	compile_bash()
{
	local	dst_dir="${LFS_SOURCES_DIR}/bash-5.2.21"
	local	sbu="0.2"
	local	package="bash"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	pushd ${dst_dir}
	./configure --prefix=/usr \
		--build=$(sh support/config.guess) \
		--host=${LFS_TGT} \
		--without-bash-malloc
	make
	make DESTDIR=${LFS} install
	[ ! -e ${LFS}/bin/sh ] && \
		ln -sv bash ${LFS}/bin/sh
	popd
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
