#!/bin/bash

function	compile_file()
{
	local	dst_dir="${LFS_SOURCES_DIR}/file-5.45"
	local	sbu="0.1"
	local	package="file"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	rm -rf ${dst_dir}
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	pushd ${dst_dir}
	take ${dst_dir}/build
	../configure --disable-bzlib \
		--disable-libseccomp \
		--disable-xzlib \
		--disable-zlib
	make
	popd
	./configure --prefix=/usr --host=${LFS_TGT} --build=$(./config.guess)
	make FILE_COMPILE=${dst_dir}/build/src/file
	make DESTDIR=${LFS} install
	rm -v ${LFS}/usr/lib/libmagic.la
	popd
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
