#!/bin/bash

function	compile_gzip()
{
	local	dst_dir="${LFS_SOURCES_DIR}/gzip-1.13"
	local	sbu="0.1"
	local	package="gzip"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	pushd ${dst_dir}
	./configure --prefix=/usr --host=${LFS_TGT}
	make
	make DESTDIR=${LFS} install
	popd
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
