#!/bin/bash

function	compile_xz()
{
	local	dst_dir="${LFS_SOURCES_DIR}/xz-5.6.0"
	local	sbu="0.1"
	local	package="xz"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	pushd ${dst_dir}
	./configure --prefix=/usr \
		--host=${LFS_TGT} \
		--build=$(build-aux/config.guess) \
		--disable-static \
		--docdir=/usr/share/doc/xz-5.4.6
	make
	make DESTDIR=${LFS} install
	rm -v $LFS/usr/lib/liblzma.la
	popd
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
