#!/bin/bash

function	compile_gawk()
{
	local	dst_dir="${LFS_SOURCES_DIR}/gawk-5.3.0"
	local	sbu="0.1"
	local	package="gawk"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	pushd ${dst_dir}
	sed -i 's/extras//' Makefile.in
	./configure --prefix=/usr \
		--host=${LFS_TGT} \
		--build=$(build-aux/config.guess)
	make
	make DESTDIR=${LFS} install
	popd
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
