#!/bin/bash

function	compile_gcc_pass2()
{
	local	dst_dir="${LFS_SOURCES_DIR}/gcc-13.2.0"
	local	sbu="4.4"
	local	package="gcc"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	pushd ${dst_dir}
	tar -xf ../${PACKAGE_FILE["mpfr"]}
	tar -xf ../${PACKAGE_FILE["gmp"]}
	tar -xf ../${PACKAGE_FILE["mpc"]}
	rm -rf mpfr && mv -v mpfr-* mpfr
	rm -rf gmp && mv -v gmp-* gmp
	rm -rf mpc && mv -v mpc-* mpc
	case ${LFS_ARCH} in
		x86_64)
			sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
		;;
	esac
	sed '/thread_header =/s/@.*@/gthr-posix.h/' \
		-i libgcc/Makefile.in libstdc++-v3/include/Makefile.in
	rm -rf ${dst_dir}/build
	take ${dst_dir}/build
	../configure \
		--build=$(../config.guess) \
		--host=${LFS_TGT} \
		--target=${LFS_TGT} \
		LDFLAGS_FOR_TARGET=-L${PWD}/${LFS_TGT}/libgcc \
		--prefix=/usr \
		--with-build-sysroot=${LFS} \
		--enable-default-pie \
		--enable-default-ssp \
		--disable-nls \
		--disable-multilib \
		--disable-libatomic \
		--disable-libgomp \
		--disable-libquadmath \
		--disable-libsanitizer \
		--disable-libssp \
		--disable-libvtv \
		--enable-languages=c,c++
	make
	make DESTDIR=${LFS} install
	[ ! -e $LFS/usr/bin/cc ] && \
		ln -sv gcc $LFS/usr/bin/cc
	popd -2
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
}
