#!/bin/bash

function	compile_ncurses()
{
	local	dst_dir="${LFS_SOURCES_DIR}/ncurses-6.4-20230520"
	local	sbu="0.3"
	local	package="ncurses"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	pushd ${dst_dir}
	sed -i s/mawk// configure
	mkdir -p build
	pushd build
	../configure
	make -C include
	make -C progs tic
	popd
	./configure --prefix=/usr \
		--host=${LFS_TGT} \
		--build=$(./config.guess) \
		--mandir=/usr/share/man \
		--with-manpage-format=normal \
		--with-shared \
		--without-normal \
		--with-cxx-shared \
		--without-debug \
		--without-ada \
		--disable-stripping \
		--enable-widec
	make
	make DESTDIR=${LFS} TIC_PATH=${dst_dir}/build/progs/tic install
	[ ! -e ${LFS}/usr/lib/libncurses.so ] && \
		ln -sv libncursesw.so ${LFS}/usr/lib/libncurses.so
	sed -e 's/^#if.*XOPEN.*$/#if 1/' -i ${LFS}/usr/include/curses.h
	popd
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
