#!/bin/bash

function	compile_coreutils()
{
	local	dst_dir="${LFS_SOURCES_DIR}/coreutils-9.4"
	local	sbu="0.3"
	local	package="coreutils"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu})s)"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	pushd ${dst_dir}
	./configure --prefix=/usr \
		--host=${LFS_TGT} \
		--build=$(build-aux/config.guess) \
		--enable-install-program=hostname \
		--enable-no-install-program=kill,uptime
	make
	make DESTDIR=${LFS} install
	mv -v ${LFS}/usr/bin/chroot ${LFS}/usr/sbin
	mkdir -pv ${LFS}/usr/share/man/man8
	mv -v ${LFS}/usr/share/man/man1/chroot.1 ${LFS}/usr/share/man/man8/chroot.8
	sed -i 's/"1"/"8"/' ${LFS}/usr/share/man/man8/chroot.8
	popd
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
