#!/bin/bash

function	compile_grep_pass1()
{
	local	dst_dir="${LFS_SOURCES_DIR}/grep-3.11"
	local	sbu="0.1"
	local	package="grep"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} pass 1 with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	pushd ${dst_dir}
	./configure --prefix=/usr \
		--host=${LFS_TGT} \
		--build=$(build-aux/config.guess)
	make
	make DESTDIR=${LFS} install
	popd
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${dst_dir}
}
