#!/bin/bash

function	configure_network()
{
	local	in="${1:-eth0}"
	local	in_ip="${2:-192.168.1.10}"
	local	gate_ip="${3:-192.168.1.1}"
	local	broad_ip="${4:-192.168.1.255}"
	local	prefix="${5:-24}"
	local	in_file="/etc/sysconfig/ifconfig.${in}"

	chroot_line "ONBOOT=yes" "${in_file}" 1
	chroot_line "IFACE=${in}" "${in_file}"
	chroot_line "SERVICE=ipv4-static" "${in_file}"
	chroot_line "IP=${in_ip}" "${in_file}"
	chroot_line "GATEWAY=${gate_ip}" "${in_file}"
	chroot_line "PREFIX=${prefix}" "${in_file}"
	chroot_line "BROADCAST=${broad_ip}" "${in_file}"
}
