#!/usr/bin/bash

function	configure_dns()
{
	local	dns_file="${LFS}/etc/resolv.conf"

	# Setup DNS
	cat > "${dns_file}" <<-EOCONF
		# Begin default ${dns_file}

		nameserver ${LFS_NET_DNS_PRI}
	EOCONF

	if [ "${LFS_NET_DNS_SEC:-}" != "" ]; then
		echo "nameserver ${LFS_NET_DNS_SEC}" >> "${dns_file}"
	fi

	echo -e "\n# End default ${dns_file}" >> "${dns_file}"
}
