#!/usr/bin/bash

function	configure_network_sysvinit()
{
	local	in_file="${LFS}/etc/sysconfig/ifconfig.${LFS_NET_INTERFACE}"

	cat_default_file "${in_file}" <<-EOIFCONFIG
		ONBOOT=yes
		IFACE=${LFS_NET_INTERFACE}
		SERVICE=ipv4-static
		IP=${LFS_NET_STATIC_IP}
		GATEWAY=${LFS_NET_STATIC_GATE}
		PREFIX=${LFS_NET_STATIC_PREF}
		BROADCAST=${LFS_NET_STATIC_BROA}
	EOIFCONFIG
}
