#!/usr/bin/bash

function	configure_console_sysvinit()
{
	# envsubst NEED single quote
	# shellcheck disable=SC2016
	cat_default_file "${LFS}/etc/sysconfig/console" \
		< <(envsubst '$LFS_CONSOLE_UNICODE,$LFS_CONSOLE_FONT,$LFS_CONSOLE_KEYMAP,$LFS_CONSOLE_LOGLVL' \
			< "${DIR_FILE}/console/sysvinit")
}
