#!/usr/bin/bash

function	configure_console_systemd()
{
	# envsubst NEED single quote
	# shellcheck disable=SC2016
	cat_default_file "${LFS}/etc/vconsole.conf" \
		< <(envsubst '$LFS_CONSOLE_KEYMAP,$LFS_CONSOLE_FONT' \
			< "${DIR_FILE}/console/systemd")
}
