#!/usr/bin/bash

function	configure_locale()
{
	# envsubst NEED single quote
	# shellcheck disable=SC2016
	cat_default_file "${LFS}/etc/locale.conf" \
		< <(envsubst '$LFS_LOCALE_LANG' < "${DIR_FILE}/locale.conf")

	# envsubst NEED single quote
	# shellcheck disable=SC2016
	cat_default_file "${LFS}/etc/profile" \
		< <(envsubst '$LFS_LOCALE_LANG' < "${DIR_FILE}/profile/lfs")
}
