#!/usr/bin/bash

function	configure_rc_site()
{
	# envsubst NEED single quote
	# shellcheck disable=SC2016
	cat_default_file "${LFS}/etc/sysconfig/rc.site" \
		< <(envsubst '$LFS_DISTRO,$LFS_DISTRO_CONTACT,$LFS_DISTRO_MINI' \
			< "${DIR_FILE}/rc.site")
}
