#!/usr/bin/bash

function	configure_network_systemd()
{
	local	in_file="${LFS}/etc/systemd/network/10-${LFS_NET_INTERFACE}"

	_mkdir "${LFS}/etc/systemd/network"
	if [ "${LFS_NET_USE_DHCP:-0}" == "0" ]; then
		in_file+="-static.network"; else
		in_file+="-dhcp.network"; fi

	cat > "${in_file}" <<-EOCONF
		# Begin default ${in_file}

		[Match]
		Name=${LFS_NET_INTERFACE}

		[Network]
	EOCONF

	# Setup DNS
	echo "DNS=${LFS_NET_DNS_PRI}" >> "${in_file}"
	if [ "${LFS_NET_DNS_SEC:-}" != "" ]; then
		echo "DNS=${LFS_NET_DNS_SEC}" >> "${in_file}"
	fi

	if [ "${LFS_NET_USE_DHCP:-0}" == "0" ]; then
		cat >> "${in_file}" <<-EOCONF
			Address=${LFS_NET_STATIC_IP}/${LFS_NET_STATIC_PREF}
			Gateway=${LFS_NET_STATIC_GATE}
		EOCONF
	else
		cat >> "${in_file}" <<-EOCONF
			DHCP=ipv4

			[DHCPv4]
			UseDomains=true
		EOCONF
	fi
	echo "# End default ${in_file}" >> "${in_file}"
}
