#!/usr/bin/bash

function	configure_clock_sysvinit()
{
	# envsubst NEED single quote
	# shellcheck disable=SC2016
	cat_default_file "${LFS}/etc/sysconfig/clock" \
		< <(envsubst '$LFS_CLOCK_UTC,$LFS_CLOCKPARAMS' < "${DIR_FILE}/clock")
	do_chroot cp -v --remove-destination "/usr/share/zoneinfo/${LFS_TZ}" /etc/localtime
}
