#!/usr/bin/bash

function	clean_basic_soft()
{
	pinfo "Cleaning basic system soft"
	do_chroot "rm -rf /tmp/* \
	&& find /usr/lib /usr/libexec -name \*.la -delete \
	&& find /usr -depth -name ${LFS_ARCH}-lfs-linux-gnu\* | xargs rm -rf \
	&& userdel -r tester"
}
