#!/usr/bin/bash

function	compile_check()
{
	package_init check 1.6

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr --disable-static \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make docdir=/usr/share/doc/check-${package_version} install"

	package_clean
}
