#!/bin/bash

function	compile_xml_parser()
{
	package_init xml-parser 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& perl Makefile.PL \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make test || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
