#!/bin/bash

function	compile_gdbm()
{
	package_init gdbm 0.1

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--enable-libgdbm-compat \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
