#!/usr/bin/bash

function	compile_libcap()
{
	package_init libcap 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& sed -i '/install -m.*STA/d' libcap/Makefile \
	&& make prefix=/usr lib=lib"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make test || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make prefix=/usr lib=lib install"

	package_clean
}
