#!/bin/bash

function	compile_iproute2()
{
	package_init iproute2 0.1

	do_chroot "cd /sources/${package_tar_folder} \
	&& sed -i /ARPD/d Makefile \
	&& rm -fv man/man8/arpd.8 \
	&& make NETNS_RUN_DIR=/run/netns \
	&& make SBINDIR=/usr/sbin install \
	&& mkdir -pv /usr/share/doc/iproute2-${package_version} \
	&& cp -v COPYING README* /usr/share/doc/iproute2-${package_version}"

	package_clean
}
