#!/usr/bin/bash

function	compile_findutils_pass2()
{
	package_init findutils 0.4 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--localstatedir=/var/lib/locate \
	&& make \
	&& make install"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& chown -R tester . \
			&& su tester -c \"PATH=\$PATH make check || true\""
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
