#!/usr/bin/bash

function	compile_gawk_pass2()
{
	package_init gawk 0.1 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& sed -i 's/extras//' Makefile.in \
	&& ./configure --prefix=/usr \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder}
			&& chown -R tester . \
			&& su tester -c \"PATH=\${PATH} make check || true\" \
			&& rm -f /usr/bin/gawk-${package_version}"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& ln -sfv gawk.1 /usr/share/man/man1/awk.1 \
		&& mkdir -pv /usr/share/doc/gawk-${package_version} \
		&& cp -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-${package_version}"

	package_clean
}
