#!/bin/bash

function	compile_flit_core()
{
	package_init flit-core 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& pip3 wheel \
		-w dist \
		--no-cache-dir \
		--no-build-isolation \
		--no-deps \
		\${PWD} \
	&& pip3 install \
		--no-index \
		--no-user \
		--find-links dist \
		flit_core"

	package_clean
}
