#!/usr/bin/bash

function	compile_gettext_pass2()
{
	package_init gettext 1.4 2

	# Exported variable
	# shellcheck disable=SC2154
	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/gettext-${package_version} \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& chmod -v 0755 /usr/lib/preloadable_libintl.so"

	package_clean
}
