#!/bin/bash

function	compile_grep_pass2()
{
	package_init grep 0.4 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& sed -i 's/echo/#echo/' src/egrep.sh \
	&& ./configure --prefix=/usr \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
