#!/bin/bash

function	compile_python_pass2()
{
	package_init python 1.8 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--enable-shared \
		--with-system-expat \
		--enable-optimizations \
	&& make \
	&& make install"
	chroot_line "[global]" /etc/pip.conf 1
	chroot_line "root-user-action = ignore" /etc/pip.conf
	chroot_line "disable-pip-version-check = true" /etc/pip.conf
	do_chroot "cd /sources/${package_tar_folder} \
	&& install -v -dm755 /usr/share/doc/python-${package_version}/html \
	&& tar --no-same-owner -xvf /sources/${PACKAGE_FILE[python-doc]} \
	&& cp -R --no-preserve=mode ${PACKAGE_TAR_FOLDER[python-doc]}/* \
		/usr/share/doc/python-${package_version}/html"

	package_clean
}
