#!/usr/bin/bash

function	compile_acl()
{
	package_init acl 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/acl-${package_version} \
	&& make \
	&& make install"

	package_clean
}
