#!/usr/bin/bash

function	compile_automake()
{
	package_init automake 1.6

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--docdir=/usr/share/doc/automake-${package_version} \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
