#!/bin/bash

function	compile_gettext_pass2()
{
	local	dst_dir="gettext-0.22.5"
	local	sbu="1.4"
	local	package="gettext"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} pass 2 with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/gettext-0.22.5 \
	&& make \
	&& make check \
	&& make install \
	&& chmod -v 0755 /usr/lib/preloadable_libintl.so"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
