#!/usr/bin/bash

function	compile_bc()
{
	package_init bc 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& CC=gcc ./configure --prefix=/usr -G -O3 -r \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
