#!/usr/bin/bash

function	compile_kmod()
{
	package_init kmod 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--sysconfdir=/etc \
		--with-openssl \
		--with-xz \
		--with-zstd \
		--with-zlib \
	&& make \
	&& make install \
	&& for target in depmod insmod modinfo modprobe rmmod; do \
		ln -sfv ../bin/kmod /usr/sbin/\$target; \
	done \
	&& ln -sfv kmod /usr/bin/lsmod"

	package_clean
}
