#!/bin/bash

function	compile_gcc_pass3()
{
	package_init gcc 42 3 1

	do_chroot "cd /sources/${package_tar_folder} \
	&& case ${LFS_ARCH} in \
		x86_64) \
			sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64 \
		;; \
	esac \
	&& mkdir -vp build && cd build \
	&& ../configure --prefix=/usr \
		LD=ld \
		--enable-languages=c,c++ \
		--enable-default-pie \
		--enable-default-ssp \
		--disable-multilib \
		--disable-bootstrap \
		--disable-fixincludes \
		--with-system-zlib \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder}/build \
			&& ulimit -s 32768 && ulimit -f 1000000 \
			&& chown -R tester . \
			&& su tester -c 'PATH=\${PATH} make -k check || true' \
			&& ../contrib/test_summary | grep -A7 Summ | grep -v '^#' "
	fi

	do_chroot "cd /sources/${package_tar_folder}/build \
		&& make install \
		&& chown -v -R root:root \
			/usr/lib/gcc/\$(gcc -dumpmachine)/${package_version}/include{,-fixed} \
		&& ln -sfvr /usr/bin/cpp /usr/lib \
		&& ln -sfv gcc.1 /usr/share/man/man1/cc.1 \
		&& ln -sfv ../../libexec/gcc/\$(gcc -dumpmachine)/${package_version}/liblto_plugin.so \
			/usr/lib/bfd-plugins/ \
		&& echo 'int main(){}' > dummy.c \
		&& cc dummy.c -v -Wl,--verbose &> dummy.log \
		&& readelf -l a.out | grep ': /lib' \
		&& grep -E -o '/usr/lib.*/S?crt[1in].*succeeded' dummy.log \
		&& grep -B4 '^ /usr/include' dummy.log \
		&& grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g' \
		&& grep '/lib.*/libc.so.6 ' dummy.log \
		&& grep found dummy.log \
		&& rm -v dummy.c a.out dummy.log \
		&& mkdir -pv /usr/share/gdb/auto-load/usr/lib \
		&& mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib"

	package_clean
}
