#!/usr/bin/bash

function	compile_gmp()
{
	package_init gmp 0.3

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--enable-cxx \
		--disable-static \
		--docdir=/usr/share/doc/gmp-${package_version} \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check 2>&1 | tee gmp-check-log || true \
			&& awk '/# PASS:/{total+=\$3} ; END{print total}' gmp-check-log"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& make install-html"

	package_clean
}
