#!/usr/bin/bash

function	compile_texinfo_pass2()
{
	package_init texinfo 0.3 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& make TEXMF=/usr/share/texmf install-tex \
		&& pushd /usr/share/info \
		&& rm -v dir \
		&& for f in * ; do install-info \$f dir 2>/dev/null ; done"

	package_clean
}
