#!/bin/bash

function	compile_openssl()
{
	local	dst_dir="openssl-3.2.1"
	local	sbu="1.8"
	local	package="openssl"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./config --prefix=/usr \
		--openssldir=/etc/ssl \
		--libdir=lib \
		shared \
		zlib-dynamic \
	&& make \
	&& HARNESS_JOBS=${LFS_CORES} make test \
	&& sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile \
	&& make MANSUFFIX=ssl install \
	&& mv -v /usr/share/doc/openssl /usr/share/doc/openssl-3.2.1 \
	&& cp -vfr doc/* /usr/share/doc/openssl-3.2.1"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
