#!/bin/bash

function	compile_sysvinit()
{
	package_init sysvinit 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& patch -Np1 -i /sources/${PACKAGE_FILE['patch_sysvinit-consolidated']} \
	&& make \
	&& make install"

	package_clean
}
