#!/bin/bash

function	compile_zstd()
{
	package_init zstd 0.5

	do_chroot "cd /sources/${package_tar_folder} \
	&& make prefix=/usr"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make prefix=/usr install \
		&& rm -v /usr/lib/libzstd.a"

	package_clean
}
