#!/bin/bash

function	compile_bzip2()
{
	package_init bzip2 0 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& patch -Np1 -i /sources/${PACKAGE_FILE["patch_bzip2-documentation"]} \
	&& sed -i 's@\(ln -s -f \)\$(PREFIX)/bin/@\1@' Makefile \
	&& sed -i 's@(PREFIX)/man@(PREFIX)/share/man@g' Makefile \
	&& make -f Makefile-libbz2_so \
	&& make clean \
	&& make \
	&& make PREFIX=/usr install \
	&& cp -av libbz2.so.* /usr/lib \
	&& ln -fsv libbz2.so.${package_version} /usr/lib/libbz2.so \
	&& cp -v bzip2-shared /usr/bin/bzip2 \
	&& for i in /usr/bin/{bzcat,bunzip2}; do \
		ln -sfv bzip2 \$i; \
	done \
	&& rm -fv /usr/lib/libbz2.a"

	package_clean
}
