#!/usr/bin/bash

function	compile_coreutils_pass2()
{
	package_init coreutils 1.0 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& patch -fNp1 -i /sources/${PACKAGE_FILE[patch_coreutils-intl]} || true \
	&& sed -e '/n_out += n_hold/,+4 s|.*bufsize.*|//&|' -i src/split.c \
	&& autoreconf -fiv \
	&& FORCE_UNSAFE_CONFIGURE=1 ./configure \
		--prefix=/usr \
		--enable-no-install-program=kill,uptime \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make NON_ROOT_USERNAME=tester check-root || true\
			&& groupadd -g 102 dummy -U tester \
			&& chown -R tester . \
			&& su tester -c \"PATH=\$PATH make RUN_EXPENSIVE_TESTS=yes check || true\" \
			&& groupdel dummy"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& mv -v /usr/bin/chroot /usr/sbin \
		&& mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8 \
		&& sed -i 's/\"1\"/\"8\"/' /usr/share/man/man8/chroot.8"


	package_clean
}
