#!/usr/bin/bash

function	compile_util_linux_pass2()
{
	package_init util-linux 0.5 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& sed -i '/test_mkfds/s/^/#/' tests/helpers/Makemodule.am \
	&& ./configure --bindir=/usr/bin \
		--libdir=/usr/lib \
		--runstatedir=/run \
		--sbindir=/usr/sbin \
		--disable-chfn-chsh \
		--disable-login \
		--disable-nologin \
		--disable-su \
		--disable-setpriv \
		--disable-runuser \
		--disable-pylibmount \
		--disable-static \
		--without-python \
		--without-systemd \
		--without-systemdsystemunitdir \
		ADJTIME_PATH=/var/lib/hwclock/adjtime \
		--docdir=/usr/share/doc/util-linux-${package_version} \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& chown -R tester . \
			&& su tester -c \"make -k check || true\" "
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
