#!/bin/bash

function	compile_xz_pass2()
{
	package_init xz 0.1 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/xz-${package_version} \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
