#!/usr/bin/bash

function	compile_openssl()
{
	package_init openssl 1.8

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./config --prefix=/usr \
		--openssldir=/etc/ssl \
		--libdir=lib \
		shared \
		zlib-dynamic \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& HARNESS_JOBS=${LFS_CORES} make test || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile \
		&& make MANSUFFIX=ssl install \
		&& mv -v /usr/share/doc/openssl /usr/share/doc/openssl-${package_version} \
		&& cp -vfr doc/* /usr/share/doc/openssl-${package_version}"

	package_clean
}
