#!/bin/bash

function	compile_zstd()
{
	local	dst_dir="zstd-1.5.5"
	local	sbu="0.5"
	local	package="zstd"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& make prefix=/usr \
	&& make check \
	&& make prefix=/usr install \
	&& rm -v /usr/lib/libzstd.a"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
