#!/usr/bin/bash

function	compile_expect()
{
	package_init expect 0.2

	do_chroot "python3 -c 'from pty import spawn; spawn([\"echo\", \"okey\"])' | grep okey"
	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--with-tcl=/usr/lib \
		--enable-shared \
		--mandir=/usr/share/man \
		--with-tclinclude=/usr/include \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make test || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& ln -svf expect${package_version}/libexpect${package_version}.so /usr/lib"

	package_clean
}
