#!/bin/bash

function	compile_man_pages()
{
	package_init man-pages 0

	do_chroot "set -x && cd /sources/${package_tar_folder} \
	&& rm -v man3/crypt* \
	&& make prefix=/usr install"

	package_clean
}
