#!/usr/bin/bash

function	compile_perl_pass2()
{
	package_init perl 1.5 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& export BUILD_ZLIB=False \
	&& export BUILD_BZIP2=0 \
	&& sh Configure -des \
		-Dprefix=/usr \
		-Dvendorprefix=/usr \
		-Dprivlib=/usr/lib/perl5/${package_version}/core_perl \
		-Darchlib=/usr/lib/perl5/${package_version}/core_perl \
		-Dsitelib=/usr/lib/perl5/${package_version}/site_perl \
		-Dsitearch=/usr/lib/perl5/${package_version}/site_perl \
		-Dvendorlib=/usr/lib/perl5/${package_version}/vendor_perl \
		-Dvendorarch=/usr/lib/perl5/${package_version}/vendor_perl \
		-Dman1dir=/usr/share/man/man1 \
		-Dman3dir=/usr/share/man/man3 \
		-Dpager='/usr/bin/less -isR' \
		-Duseshrplib \
		-Dusethreads \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& TEST_JOBS=${LFS_CORES} make test_harness || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
