#!/usr/bin/bash

function	compile_readline()
{
	package_init readline 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& sed -i '/MV.*old/d' Makefile.in \
	&& sed -i '/{OLDSUFF}/c:' support/shlib-install \
	&& patch -Np1 -i /sources/${PACKAGE_FILE["patch_readline-upstream"]} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--with-curses \
		--docdir=/usr/share/doc/readline-${package_version} \
	&& make SHLIB_LIBS='-lncursesw' \
	&& make SHLIB_LIBS='-lncursesw' install \
	&& install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-${package_version}"

	package_clean
}
