#!/usr/bin/bash

function	compile_bash_pass2()
{
	package_init bash 1.2 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& patch -Np1 -i /sources/${PACKAGE_FILE["patch_bash-upstream"]} \
	&& ./configure --prefix=/usr \
		--without-bash-malloc \
		--with-installed-readline \
		--docdir=/usr/share/doc/bash-${package_version} \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		cat > "${LFS}/tmp/e" < "${DIR_FILE}/test/bash_2"
		do_chroot "cd /sources/${package_tar_folder} \
			&& chown -R tester . \
			&& su -s /usr/bin/expect tester </tmp/e || true"
		_rm "${LFS}/tmp/e"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
