#!/usr/bin/bash

function	compile_bison_pass2()
{
	package_init bison 2.3 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--docdir=/usr/share/doc/bison-${package_version} \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
