#!/bin/bash

function	compile_texinfo_pass2()
{
	local	dst_dir="texinfo-7.1"
	local	sbu="0.3"
	local	package="texinfo"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr \
	&& make \
	&& make check \
	&& make install \
	&& make TEXMF=/usr/share/texmf install-tex \
	&& pushd /usr/share/info \
	&& rm -v dir \
	&& for f in * ; do install-info \$f dir 2>/dev/null ; done \
	&& popd"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
