#!/usr/bin/bash

function	compile_wheel()
{
	package_init wheel 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& pip3 wheel \
		-w dist \
		--no-cache-dir \
		--no-build-isolation \
		--no-deps \
		\${PWD} \
	&& pip3 install \
		--no-index \
		--find-links=dist \
		wheel"

	package_clean
}
