#!/usr/bin/bash

function	compile_vim()
{
	package_init vim 2.5

	do_chroot "cd /sources/${package_tar_folder} \
	&& echo '#define SYS_VIMRC_FILE \"/etc/vimrc\"' >> src/feature.h \
	&& ./configure --prefix=/usr \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& chown -R tester . \
			&& su tester -c \"TERM=xterm-256color LANG=en_US.UTF-8 make -j1 test\" &> vim-test.log || true \""
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& ln -fsv vim /usr/bin/vi\
		&& for L in  /usr/share/man/{,*/}man1/vim.1; do \
			ln -sfv vim.1 \$(dirname \$L)/vi.1; \
		done \
		&& ln -sfv ../vim/vim91/doc /usr/share/doc/vim-9.1.0148"

	cat_default_file "${LFS}/etc/vimrc" '"' < "${DIR_FILE}/vimrc"

	package_clean
}
