#!/usr/bin/bash

function	compile_ninja()
{
	package_init ninja 0.3

	do_chroot "cd /sources/${package_tar_folder} \
	&& export NINJAJOBS=${LFS_CORES} \
	&& sed -i '/int Guess/a \
		int   j = 0; \
		char* jobs = getenv( \"NINJAJOBS\" ); \
		if ( jobs != NULL ) j = atoi( jobs ); \
		if ( j > 0 ) return j; \
		' src/ninja.cc \
	&& python3 configure.py --bootstrap"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& ./ninja ninja_test || true\
			&& ./ninja_test --gtest_filter=-SubprocessTest.SetWithLots || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& install -vm755 ninja /usr/bin/ \
		&& install -vDm644 misc/bash-completion /usr/share/bash-completion/completions/ninja \
		&& install -vDm644 misc/zsh-completion  /usr/share/zsh/site-functions/_ninja"

	package_clean
}
