#!/usr/bin/bash

function	compile_flex()
{
	package_init flex 0.1 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--docdir=/usr/share/doc/flex-${package_version} \
		--disable-static \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& ln -sfv flex /usr/bin/lex \
		&& ln -sfv flex.1 /usr/share/man/man1/lex.1"

	package_clean
}
