#!/bin/bash

function	compile_gperf()
{
	package_init gperf 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--docdir=/usr/share/doc/gperf-${package_version} \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make -j1 check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
