#!/usr/bin/bash

function	compile_ncurses_pass2()
{
	package_init ncurses 0.2 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--mandir=/usr/share/man \
		--with-shared \
		--without-debug \
		--without-normal \
		--with-cxx-shared \
		--enable-pc-files \
		--enable-widec \
		--with-pkg-config-libdir=/usr/lib/pkgconfig \
	&& make \
	&& make DESTDIR=\$PWD/dest install \
	&& install -vm755 dest/usr/lib/libncursesw.so.6.4 /usr/lib \
	&& rm -v  dest/usr/lib/libncursesw.so.6.4 \
	&& sed -e 's/^#if.*XOPEN.*$/#if 1/' -i dest/usr/include/curses.h \
	&& cp -av dest/* / \
	&& for lib in ncurses form panel menu ; do
		ln -sfv lib\${lib}w.so /usr/lib/lib\${lib}.so \
		&& ln -sfv \${lib}w.pc /usr/lib/pkgconfig/\${lib}.pc; \
	done \
	&& ln -sfv libncursesw.so /usr/lib/libcurses.so \
	&& cp -v -R doc -T /usr/share/doc/ncurses-${package_version} \
	&& make distclean \
	&& ./configure --prefix=/usr \
		--with-shared \
		--without-normal \
		--without-debug \
		--without-cxx-binding \
		--with-abi-version=5 \
	&& make sources libs \
	&& cp -av lib/lib*.so.5* /usr/lib"

	package_clean
}
