#!/usr/bin/bash

function	compile_mpc()
{
	package_init mpc 0.1

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/mpc-${package_version} \
	&& make \
	&& make html"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& make install-html"

	package_clean
}
