#!/bin/bash

function	compile_libxcrypt()
{
	package_init libxcrypt 0.1

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--enable-hashes=strong,glibc \
		--enable-obsolete-api=no \
		--disable-static \
		--disable-failure-tokens \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& make distclean \
		&& ./configure --prefix=/usr \
			--enable-hashes=strong,glibc \
			--enable-obsolete-api=glibc \
			--disable-static \
			--disable-failure-tokens \
		&& make \
		&& cp -av --remove-destination .libs/libcrypt.so.1* /usr/lib"

	package_clean
}
