#!/bin/bash

function	compile_tcl()
{
	package_init tcl 2.7

	do_chroot "cd /sources/${package_tar_folder}/unix \
	&& ./configure \
		--prefix=/usr \
		--mandir=/usr/share/man \
	&& make \
	&& sed -e 's|/sources/${dst_folder}/unix|/usr/lib|' \
		-e 's|/sources/${dst_folder}|/usr/include|' \
		-i tclConfig.sh \
	&& sed -e 's|/sources/${dst_folder}/unix/pkgs/tdbc1.1.7|/usr/lib/tdbc1.1.7|' \
		-e 's|/sources/${dst_folder}/pkgs/tdbc1.1.7/generic|/usr/include|' \
		-e 's|/sources/${dst_folder}/pkgs/tdbc1.1.7/library|/usr/lib/tcl8.6|' \
		-e 's|/sources/${dst_folder}/pkgs/tdbc1.1.7|/usr/include|' \
		-i pkgs/tdbc1.1.7/tdbcConfig.sh \
	&& sed -e 's|/sources/${dst_folder}/unix/pkgs/itcl4.2.4|/usr/lib/itcl4.2.4|' \
		-e 's|/sources/${dst_folder}/pkgs/itcl4.2.4/generic|/usr/include|' \
		-e 's|/sources/${dst_folder}/pkgs/itcl4.2.4|/usr/include|' \
		-i pkgs/itcl4.2.4/itclConfig.sh"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder}/unix \
			&& make test || true"
	fi

	do_chroot "cd /sources/${package_tar_folder}/unix \
		&& make install \
		&& chmod -v u+w /usr/lib/libtcl8.6.so \
		&& make install-private-headers \
		&& ln -sfv tclsh8.6 /usr/bin/tclsh \
		&& mv /usr/share/man/man3/{Thread,Tcl_Thread}.3 \
		&& cd .. \
		&& tar -xf /sources/${PACKAGE_FILE[tcl-doc]} --strip-components=1 \
		&& mkdir -v -p /usr/share/doc/tcl-${package_version} \
		&& cp -v -r  ./html/* /usr/share/doc/tcl-${package_version}"

	package_clean
}
