#!/bin/bash

function	compile_flex()
{
	local	dst_dir="flex-2.6.4"
	local	sbu="0.1"
	local	package="flex"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr \
		--docdir=/usr/share/doc/flex-2.6.4 \
		--disable-static \
	&& make \
	&& make check \
	&& make install \
	&& ln -sfv flex /usr/bin/lex \
	&& ln -sfv flex.1 /usr/share/man/man1/lex.1 "
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
