#!/bin/bash

function	compile_bash_pass2()
{
	package_init bash 1.2 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& patch -Np1 -i /sources/${PACKAGE_FILE["patch_bash-upstream"]} \
	&& ./configure --prefix=/usr \
		--without-bash-malloc \
		--with-installed-readline \
		--docdir=/usr/share/doc/bash-${package_version} \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		chroot_line "set timeout -1" /tmp/e 1
		chroot_line "spawn make tests" /tmp/e
		chroot_line "expect eof" /tmp/e
		chroot_line "lassign [wait] _ _ _ value" /tmp/e
		chroot_line 'exit ${value}' /tmp/e
		do_chroot "cd /sources/${package_tar_folder} \
			&& chown -R tester . \
			&& su -s /usr/bin/expect tester </tmp/e || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
