#!/bin/bash

function	compile_dejagnu()
{
	local	dst_dir="dejagnu-1.6.3"
	local	sbu="0.1"
	local	package="dejagnu"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "mkdir -vp /sources/${dst_dir}/build && cd /sources/${dst_dir}/build \
	&& ../configure --prefix=/usr \
	&& makeinfo --html --no-split -o doc/dejagnu.html ../doc/dejagnu.texi \
	&& makeinfo --plaintext -o doc/dejagnu.txt ../doc/dejagnu.texi \
	&& make check \
	&& make install \
	&& install -v -dm755 /usr/share/doc/dejagnu-1.6.3 \
	&& install -v -m644 doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-1.6.3"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
