#!/bin/bash

function	compile_sed_pass2()
{
	package_init sed 0.3 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
	&& make \
	&& make html"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& chown -R tester . \
			&& su tester -c 'PATH=\${PATH} make check || true' "
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& install -d -m755 /usr/share/doc/sed-${package_version} \
		&& install -m644 doc/sed.html /usr/share/doc/sed-${package_version}"

	package_clean
}
