#!/usr/bin/bash

function	compile_libelf()
{
	package_init elfutils 0.3

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--disable-debuginfod \
		--enable-libdebuginfod=dummy \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make test || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make -C libelf install \
		&& install -vm644 config/libelf.pc /usr/lib/pkgconfig \
		&& rm /usr/lib/libelf.a"

	package_clean
}
