#!/bin/bash

function	compile_intltool()
{
	local	dst_dir="intltool-0.51.0"
	local	sbu="0.05"
	local	package="intltool"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU less than 0.1 ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& sed -i 's:\\\${:\\\$\\{:' intltool-update.in \
	&& ./configure --prefix=/usr \
	&& make \
	&& make check \
	&& make install \
	&& install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/intltool-0.51.0/I18N-HOWTO"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
