#!/usr/bin/bash

function	compile_sysklogd()
{
	package_init sysklogd 0 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& sed -i '/Error loading kernel symbols/{n;n;d}' ksym_mod.c \
	&& sed -i 's/union wait/int/' syslogd.c \
	&& make \
	&& make BINDIR=/sbin install"

	cat_default_file "${LFS}/etc/syslog.conf" < "${DIR_FILE}/syslog.conf"

	package_clean
}
