#!/usr/bin/bash

function	compile_procps_ng()
{
	package_init procps-ng 0.1

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--docdir=/usr/share/doc/procps-ng-${package_version} \
		--disable-static \
		--disable-kill \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make -k check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
