#!/bin/bash

function	compile_kbd()
{
	package_init kbd 0.1

	do_chroot "cd /sources/${package_tar_folder} \
	&& patch -Np1 -i /sources/${PACKAGE_FILE['patch_kbd-backspace']} \
	&& sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure \
	&& sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in \
	&& ./configure --prefix=/usr \
		--disable-vlock \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& cp -R -v docs/doc -T /usr/share/doc/kbd-${package_version}"

	package_clean
}
