#!/bin/bash

function	compile_readline()
{
	local	dst_dir="readline-8.2"
	local	sbu="0.05"
	local	package="readline"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU less than 0.1 ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& sed -i '/MV.*old/d' Makefile.in \
	&& sed -i '/{OLDSUFF}/c:' support/shlib-install \
	&& patch -Np1 -i /sources/${PATCH_FILE["readline-upstream"]} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--with-curses \
		--docdir=/usr/share/doc/readline-8.2 \
	&& make SHLIB_LIBS='-lncursesw' \
	&& make SHLIB_LIBS='-lncursesw' install \
	&& install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-8.2"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
