#!/bin/bash

function	compile_perl_pass2()
{
	local	dst_dir="perl-5.38.2"
	local	sbu="1.5"
	local	package="perl"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} pass 2 with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& export BUILD_ZLIB=False \
	&& export BUILD_BZIP2=0 \
	&& sh Configure -des \
		-Dprefix=/usr \
		-Dvendorprefix=/usr \
		-Dprivlib=/usr/lib/perl5/5.38.2/core_perl \
		-Darchlib=/usr/lib/perl5/5.38.2/core_perl \
		-Dsitelib=/usr/lib/perl5/5.38.2/site_perl \
		-Dsitearch=/usr/lib/perl5/5.38.2/site_perl \
		-Dvendorlib=/usr/lib/perl5/5.38.2/vendor_perl \
		-Dvendorarch=/usr/lib/perl5/5.38.2/vendor_perl \
		-Dman1dir=/usr/share/man/man1 \
		-Dman3dir=/usr/share/man/man3 \
		-Dpager='/usr/bin/less -isR' \
		-Duseshrplib \
		-Dusethreads \
	&& make"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	pinfo "Testing ${PACKAGE_FILE[${package}]::-7} with SBU 11 ($(get_sbu 11))"
	do_chroot "cd /sources/${dst_dir} \
	&& TEST_JOBS=${LFS_CORES} make test_harness"
	ppass "Tested ${PACKAGE_FILE[${package}]::-7}"
	pinfo "Installing ${PACKAGE_FILE[${package}]::-7}"
	do_chroot "cd /sources/${dst_dir} && make install"
	ppass "Installed ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
