#!/usr/bin/bash

function	compile_grub()
{
	package_init grub 0.3

	do_chroot "cd /sources/${package_tar_folder} \
	&& unset {C,CPP,CXX,LD}FLAGS \
	&& echo depends bli part_gpt > grub-core/extra_deps.lst \
	&& ./configure --prefix=/usr \
		--sysconfdir=/etc \
		--disable-efiemu \
		--disable-werror \
	&& make \
	&& make install \
	&& mv -v /etc/bash_completion.d/grub /usr/share/bash-completion/completions"

	package_clean
}
