#!/usr/bin/bash

function	compile_binutils_pass3()
{
	package_init binutils 2.2 3

	_mkdir "${dst_folder}/build"
	do_chroot "cd /sources/${package_tar_folder}/build \
	&& ../configure --prefix=/usr \
		--sysconfdir=/etc \
		--enable-gold \
		--enable-ld=default \
		--enable-plugins \
		--enable-shared \
		--disable-werror \
		--enable-64-bit-bfd \
		--with-system-zlib \
		--enable-default-hash-style=gnu \
	&& make tooldir=/usr"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder}/build \
			&& make -k check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder}/build \
		&& make tooldir=/usr install \
		&& rm -fv /usr/lib/lib{bfd,ctf,ctf-nobfd,gprofng,opcodes,sframe}.a"

	package_clean
}
