#!/bin/bash

function	compile_sed_pass2()
{
	local	dst_dir="sed-4.9"
	local	sbu="0.3"
	local	package="sed"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} pass 2 with SBU ${sbu} ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr \
	&& make \
	&& make html \
	&& chown -R tester . \
	&& su tester -c 'PATH=\${PATH} make check' \
	&& make install \
	&& install -d -m755 /usr/share/doc/sed-4.9 \
	&& install -m644 doc/sed.html /usr/share/doc/sed-4.9"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
