#!/bin/bash

function	compile_dejagnu()
{
	package_init dejagnu 0.1

	_mkdir ${dst_folder}/build
	do_chroot "cd /sources/${package_tar_folder}/build \
	&& ../configure --prefix=/usr \
	&& makeinfo --html --no-split -o doc/dejagnu.html ../doc/dejagnu.texi \
	&& makeinfo --plaintext -o doc/dejagnu.txt ../doc/dejagnu.texi"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder}/build \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder}/build \
		&& make install \
		&& install -v -dm755 /usr/share/doc/dejagnu-${package_version} \
		&& install -v -m644 doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-${package_version}"

	package_clean
}
