#!/bin/bash

function	compile_zlib()
{
	package_init zlib 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& rm -fv /usr/lib/libz.a"

	package_clean
}
