#!/bin/bash

function	compile_file_pass2()
{
	package_init file 0 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
