#!/bin/bash

function	compile_dbus()
{
	package_init dbus 0.1

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --runstatedir=/run \
            --enable-user-session \
            --disable-static \
            --disable-doxygen-docs \
            --disable-xml-docs \
            --docdir=/usr/share/doc/dbus-${package_version} \
            --with-system-socket=/run/dbus/system_bus_socket \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& ln -sfv /etc/machine-id /var/lib/dbus"

	package_clean
}
