#!/usr/bin/bash

function	compile_groff()
{
	package_init groff 0.2

	do_chroot "cd /sources/${package_tar_folder} \
	&& PAGE=A4 ./configure --prefix=/usr \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
