#!/usr/bin/bash

function	compile_expat()
{
	package_init expat 0.1

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/expat-${package_version} \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& install -v -m644 doc/*.{html,css} /usr/share/doc/expat-${package_version}"

	package_clean
}
