#!/bin/bash

function	compile_meson()
{
	package_init meson 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps \${PWD} \
	&& pip3 install --no-index --find-links dist meson \
	&& install -vDm644 data/shell-completions/bash/meson /usr/share/bash-completion/completions/meson \
	&& install -vDm644 data/shell-completions/zsh/_meson /usr/share/zsh/site-functions/_meson"

	package_clean
}
