#!/bin/bash

function	compile_less()
{
	package_init less 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr --sysconfdir=/etc \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
