#!/usr/bin/bash

function	compile_inetutils()
{
	package_init inetutils 0.2

	do_chroot "cd /sources/${package_tar_folder} \
	&& echo '#define PATH_PROCNET_DEV \"/proc/net/dev\"' >> ifconfig/system/linux.h \
	&& ./configure --prefix=/usr \
		--bindir=/usr/bin \
		--localstatedir=/var \
		--disable-logger \
		--disable-whois \
		--disable-rcp \
		--disable-rexec \
		--disable-rlogin \
		--disable-rsh \
		--disable-servers \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& mv -v /usr/{,s}bin/ifconfig"

	package_clean
}
