#!/bin/bash

function	compile_pkgconf()
{
	local	dst_dir="pkgconf-2.1.1"
	local	sbu="0.05"
	local	package="pkgconf"

	pinfo "Building ${PACKAGE_FILE[${package}]::-7} with SBU less than 0.1 ($(get_sbu ${sbu}))"
	tar -xf ${LFS_SOURCES_DIR}/${PACKAGE_FILE[${package}]} -C ${LFS_SOURCES_DIR}
	do_chroot "cd /sources/${dst_dir} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/pkgconf-2.1.1 \
	&& make \
	&& make install \
	&& ln -sfv pkgconf /usr/bin/pkg-config \
	&& ln -sfv pkgconf.1 /usr/share/man/man1/pkg-config.1"
	ppass "Builded ${PACKAGE_FILE[${package}]::-7}"
	rm -rf ${LFS_SOURCES_DIR}/${dst_dir}
}
