#!/bin/bash

function	compile_libtool()
{
	package_init libtool 1.2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make -k check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& rm -fv /usr/lib/libltdl.a"

	package_clean
}
