#!/usr/bin/bash

function	compile_markupsafe()
{
	package_init markup-safe 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& pip3 wheel \
		-w dist \
		--no-cache-dir \
		--no-build-isolation \
		--no-deps \
		\${PWD} \
	&& pip3 install \
		--no-index \
		--no-user \
		--find-links dist \
		Markupsafe"

	package_clean
}
