#!/bin/bash

function	compile_intltool()
{
	package_init intltool 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& sed -i 's:\\\${:\\\$\\{:' intltool-update.in \
	&& ./configure --prefix=/usr \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/intltool-${package_version}/I18N-HOWTO"

	package_clean
}
