#!/bin/bash

function	compile_sysklogd()
{
	package_init sysklogd 0 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& sed -i '/Error loading kernel symbols/{n;n;d}' ksym_mod.c \
	&& sed -i 's/union wait/int/' syslogd.c \
	&& make \
	&& make BINDIR=/sbin install"

	chroot_line "# Begin default /etc/syslog.conf" /etc/syslog.conf 1
	chroot_line "" /etc/syslog.conf
	chroot_line "auth,authpriv.* -/var/log/auth.log" /etc/syslog.conf
	chroot_line "*.*;auth,authpriv.none -/var/log/sys.log" /etc/syslog.conf
	chroot_line "daemon.* -/var/log/daemon.log" /etc/syslog.conf
	chroot_line "kern.* -/var/log/kern.log" /etc/syslog.conf
	chroot_line "mail.* -/var/log/mail.log" /etc/syslog.conf
	chroot_line "user.* -/var/log/user.log" /etc/syslog.conf
	chroot_line "*.emerg *" /etc/syslog.conf
	chroot_line "" /etc/syslog.conf
	chroot_line "# End default /etc/syslog.conf" /etc/syslog.conf

	package_clean
}
