#!/usr/bin/bash

function	compile_tar_pass2()
{
	package_init tar 0.5 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install \
		&& make -C doc install-html docdir=/usr/share/doc/tar-${package_version}"

	package_clean
}
