#!/bin/bash

function	compile_pkgconf()
{
	package_init pkgconf 0

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
		--disable-static \
		--docdir=/usr/share/doc/pkgconf-${package_version} \
	&& make \
	&& make install \
	&& ln -sfv pkgconf /usr/bin/pkg-config \
	&& ln -sfv pkgconf.1 /usr/share/man/man1/pkg-config.1"

	package_clean
}
