#!/usr/bin/bash

function	compile_systemd()
{
	package_init systemd 0.2

	do_chroot "cd /sources/${package_tar_folder} \
	&& sed -i -e 's/GROUP=\"render\"/GROUP=\"video\"/' \
       -e 's/GROUP=\"sgx\", //' rules.d/50-udev-default.rules.in \
	&& patch -Np1 -i /sources/${PACKAGE_FILE[patch_systemd-upstream]} \
	&& ./configure --prefix=/usr \
	&& mkdir -vp build && cd build \
	&& meson setup \
		--prefix=/usr                 \
		--buildtype=release           \
		-Ddefault-dnssec=no           \
		-Dfirstboot=false             \
		-Dinstall-tests=false         \
		-Dldconfig=false              \
		-Dsysusers=false              \
		-Drpmmacrosdir=no             \
		-Dhomed=disabled              \
		-Duserdb=false                \
		-Dman=disabled                \
		-Dmode=release                \
		-Dpamconfdir=no               \
		-Ddev-kvm-mode=0660           \
		-Dnobody-group=nogroup        \
		-Dsysupdate=disabled          \
		-Dukify=disabled              \
		-Ddocdir=/usr/share/doc/systemd-255 \
		.. \
	&& ninja \
	&& ninja install \
	&& tar -xf /sources/${PACKAGE_FILE[systemd-man-pages]} \
	    --no-same-owner --strip-components=1   \
    	-C /usr/share/man \
	&& systemd-machine-id-setup \
	&& systemctl preset-all"

	package_clean
}
