#!/usr/bin/bash

function	compile_m4_pass2()
{
	package_init m4 0.3 2

	do_chroot "cd /sources/${package_tar_folder} \
	&& ./configure --prefix=/usr \
	&& make \
	&& make check \
	&& make install"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder} \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder} \
		&& make install"

	package_clean
}
