#!/bin/bash

function	compile_e2fsprogs()
{
	package_init e2fsprogs 2.4

	_mkdir ${dst_folder}/build
	do_chroot "cd /sources/${package_tar_folder}/build \
	&& ../configure --prefix=/usr \
		--sysconfdir=/etc \
		--enable-elf-shlibs \
		--disable-libblkid \
		--disable-libuuid \
		--disable-uuidd \
		--disable-fsck \
	&& make"

	if [ "${LFS_DO_TEST:-1}" == "1" ]; then
		do_chroot "cd /sources/${package_tar_folder}/build \
			&& make check || true"
	fi

	do_chroot "cd /sources/${package_tar_folder}/build \
		&& make install \
		&& rm -fv /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a \
		&& gunzip -v /usr/share/info/libext2fs.info.gz \
		&& install-info --dir-file=/usr/share/info/dir /usr/share/info/libext2fs.info \
		&& makeinfo -o doc/com_err.info ../lib/et/com_err.texinfo \
		&& install -v -m644 doc/com_err.info /usr/share/info \
		&& install-info --dir-file=/usr/share/info/dir /usr/share/info/com_err.info"

	package_clean
}
