#!/usr/bin/bash

function	checkup()
{
	# Install dependencies
	/sbin/apk add --update \
		vim \
		binutils \
		bison \
		gcc \
		g++ \
		make \
		patch \
		texinfo \
		gawk \
		curl

	pinfo "Symlink /bin/sh to /bin/bash"
	[ /bin/sh -ef /bin/bash ] || (_rm /bin/sh; _ln -s /bin/bash /bin/sh)

	# # Check if all good
	# pinfo "Check all good with LFS script"

	# if bash "${DIR_SCRIPT}/version-check.sh"; then
	# 	ppass "version-check.sh pass"
	# else
	# 	pfail "Error: version-check.sh failed"
	# 	exit 1
	# fi
}
