#!/bin/bash

function	create_minimal_fhs()
{
	pinfo "Create directory layout"
	mkdir -p ${LFS}/{etc,var,tools} ${LFS}/usr/{bin,lib,sbin}
	for i in bin lib sbin; do
		[ -e ${LFS}/${i} ] && _rm ${LFS}/${i}
		_ln -s usr/${i} ${LFS}/
	done
	case ${LFS_ARCH} in
		x86_64)
			[ -e ${LFS}/lib64 ] && _rm ${LFS}/lib64
			_ln -s lib ${LFS}/lib64
		;;
	esac
}

