#!/usr/bin/bash

function	download_sources()
{
	declare -g DOWNLOAD_DONE="${DOWNLOAD_DONE:-0}"
	[ "${DOWNLOAD_DONE}" == "1" ] && return

	pinfo "Download sources"
	_mkdir "${LFS_SOURCES_DIR}"
	_mkdir "${DIR_DOWNLOAD_CACHE}"
	chmod -v a+wt "${LFS_SOURCES_DIR}"
	PACKAGE_ID=1
	for pack in "${PACKAGE[@]}"; do
		get_file "${pack}"
		((PACKAGE_ID++)) || true
	done
	DOWNLOAD_DONE=1
}
