#!/bin/bash

function	download_sources()
{
	pinfo "Download sources"
	_mkdir "${LFS_SOURCES_DIR}"
	_mkdir ".sources"
	chmod -v a+wt "${LFS_SOURCES_DIR}"
	for pack in ${PACKAGE[@]}; do
		get_file "${pack}"
	done
}
