#!/usr/bin/bash

function	partition_lfs()
{
	lfs_umount

	# envsubst NEED single quote
	# shellcheck disable=SC2016
	sfdisk "${TARGET_DISK}" \
		< <(envsubst '$TARGET_SWAP_SIZE'< "${DIR_FILE}/default_disk_map")

	pinfo "Make filesystem"
	echo y | mkfs -v -t ext4 "${TARGET_DISK}1"
	mkswap "${TARGET_DISK}2"
	echo y | mkfs -v -t ext4 "${TARGET_DISK}3"
}
