#!/bin/bash

ESC="\x1b"
CSI="${ESC}["

CUR_SAV="${ESC}7"
CUR_RES="${ESC}8"
CLR_LINE="${CSI}2K"
CLR_SCREEN="${CSI}2J"
VID_ENA="${CSI}?1049h"
VID_DIS="${CSI}?1049l"
CUR_ENA="${CSI}?25h"
CUR_DIS="${CSI}?25l"

RED="${CSI}31m"
GRE="${CSI}32m"
YEL="${CSI}33m"
BLU="${CSI}34m"
PUR="${CSI}35m"
CYA="${CSI}36m"
RST="${CSI}0m"

BOL="${CSI}1m"
RST_BOL="${CSI}22m"

HDR_PASS="[${GRE}+${RST}]"
HDR_FAIL="[${RED}-${RST}]"
HDR_WARN="[${RED}!${RST}]"
HDR_INFO="[${BLU}*${RST}]"
HDR_TITLE="[${BOL}${YEL}#${RST}${RST_BOL}]"
