#!/bin/bash

function	do_chroot()
{
	sudo chroot "/mnt/lfs" /usr/bin/env -i \
		HOME=/root \
		TERM="${TERM}" \
		PS1='(lfs chroot) \u:\w\$ ' \
		PATH=/usr/bin:/usr/sbin \
		MAKEFLAGS="-j${LFS_CORES}" \
		TESTSUITEFLAGS="-j${LFS_CORES}" \
		/bin/bash <<<${@}
}

function	chroot_line()
{
	local	line="${1}"
	local	file="${2}"
	local	replace="${3:-0}"
	if [ "${replace}" == "1" ]; then
		replace=">"
	else
		replace=">>"
	fi

	sudo chroot "/mnt/lfs" /usr/bin/env -i \
		HOME=/root \
		TERM="${TERM}" \
		PS1='(lfs chroot) \u:\w\$ ' \
		PATH=/usr/bin:/usr/sbin \
		MAKEFLAGS="-j${LFS_CORES}" \
		TESTSUITEFLAGS="-j${LFS_CORES}" \
		/usr/bin/bash <<<"echo '${line}' ${replace} ${file}"
}
