#!/bin/bash

function	clean_lfs()
{
	do_chroot rm -rf /usr/share/{info,man,doc}/*
	do_chroot find /usr/{lib,libexec} -name \*.la -delete
	do_chroot rm -rf /tools
	mountpoint -q ${LFS}/dev/shm && umount -v ${LFS}/dev/shm || true
	umount -v ${LFS}/dev/pts || true
	umount -v ${LFS}/{sys,proc,run,dev} || true
}

function	backup_lfs()
{
	local	desc="${1:-}"
	local	file="lfs-${LFS_VERSION}-${LFS_CODENAME}-${desc}-$(date +%d%m%Y%H%M%S).tar.xz"

	clean_lfs
	_pushd ${LFS}
	pinfo "Creating backup ${file}"
	_tar -cJpf ${DIR_BASE}/${file} .
	ppass "Backup done"
	mount_lfs
	create_virtualfs
	_popd ${LFS}
}

function	restore()
{
	: # TODO
}
