#!/bin/bash

function	clean_lfs()
{
	do_chroot rm -rf /usr/share/{info,man,doc}/*
	do_chroot find /usr/{lib,libexec} -name \*.la -delete
	do_chroot rm -rf /tools
	mountpoint -q ${LFS}/dev/shm && umount -v ${LFS}/dev/shm || true
	umount -v ${LFS}/dev/pts || true
	umount -v ${LFS}/{sys,proc,run,dev} || true
	find ${LFS}/sources/* -type d -exec rm -rf {} \; || true
}

function	backup_lfs()
{
	local	file_desc="${1:-}"
	local	file="lfs-${LFS_VERSION}-${LFS_CODENAME}-${PACKAGE_VERSION[linux]}"
	[ "${LFS_GIT_VERSION}" != "" ] && file+="-${LFS_GIT_VERSION}"
	[ "${file_desc}" != "" ] && file+="-${file_desc}"
	file+="-$(date +%d%m%Y%H%M%S).tar.gz"

	clean_lfs
	_pushd ${LFS}
	pinfo "Creating backup ${file}"
	dset "${BOL}${CYA}Creating backup ${GRE}${file}${RST}${RST_BOL}"
	# GZIP MAXED
	env GZIP=-9 tar -czpf "${DIR_BASE}/${file}" .
	# BZIP2
	# tar -cjpf "${DIR_BASE}/${file}" .
	# XZ ...
	# tar -czpf "${DIR_BASE}/${file}" .
	ppass "Backup done"

	mount_lfs
	create_virtualfs
	_popd
}

function	restore()
{
	: # TODO
}
