#!/bin/bash

function	clean_lfs()
{
	do_chroot rm -rf /usr/share/{info,man,doc}/*
	do_chroot find /usr/{lib,libexec} -name \*.la -delete
	do_chroot rm -rf /tools
	mountpoint -q ${LFS}/dev/shm && umount -v ${LFS}/dev/shm || true
	umount -v ${LFS}/dev/pts || true
	umount -v ${LFS}/{sys,proc,run,dev} || true
}

function	backup_lfs()
{
	local	chap="${1:-}"

	cd ${LFS}
	pinfo "Creating backup"
	tar -cJpf ${DIR_BASE}/lfs-${chap}-12.1_$(date +%d%m%Y%H%M%S).tar.xz .
	ppass "Backup done"
}

function	restore()
{
	: # TODO
}
