#!/usr/bin/bash

# Main utils
source "${DIR_SRC}/utils/lifovar"
source "${DIR_SRC}/utils/print"
source "${DIR_SRC}/utils/misc"
source "${DIR_SRC}/utils/sbu"
source "${DIR_SRC}/utils/backup_restore"
source "${DIR_SRC}/utils/lfs"
source "${DIR_SRC}/utils/blfs"
source "${DIR_SRC}/utils/summary"
source "${DIR_SRC}/utils/step"
source "${DIR_SRC}/utils/trap"
source "${DIR_SRC}/utils/ansi"
source "${DIR_SRC}/utils/daemon_status"
source "${DIR_SRC}/utils/create_user"
source "${DIR_SRC}/utils/dot_mngr_helper"

source "${DIR_LFS}/do_lfs"

source "${DIR_LFS}/01_prepare/checkup"
source "${DIR_LFS}/01_prepare/partition"
source "${DIR_LFS}/01_prepare/download_sources"
source "${DIR_LFS}/01_prepare/create_minimal_fhs"

source "${DIR_LFS}/02_cross_toolchain/fix_linux_headers"

source "${DIR_LFS}/04_chroot_additional_tool/change_ownership"
source "${DIR_LFS}/04_chroot_additional_tool/create_full_fhs"
source "${DIR_LFS}/04_chroot_additional_tool/essential_file"
source "${DIR_LFS}/04_chroot_additional_tool/clean_temp_lfs"

source "${DIR_LFS}/05_basic_system_soft/configure_glibc_pass2"
source "${DIR_LFS}/05_basic_system_soft/configure_python3_pass2"
source "${DIR_LFS}/05_basic_system_soft/configure_vim_pass1"
source "${DIR_LFS}/05_basic_system_soft/configure_sysklogd"
source "${DIR_LFS}/05_basic_system_soft/strip_binaries"
source "${DIR_LFS}/05_basic_system_soft/clean_basic_soft"

source "${DIR_LFS}/06_system_config/configure_devices"
source "${DIR_LFS}/06_system_config/configure_network_sysvinit"
source "${DIR_LFS}/06_system_config/configure_network_systemd"
source "${DIR_LFS}/06_system_config/configure_dns"
source "${DIR_LFS}/06_system_config/configure_sysvinit"
source "${DIR_LFS}/06_system_config/configure_clock_sysvinit"
source "${DIR_LFS}/06_system_config/configure_clock_systemd"
source "${DIR_LFS}/06_system_config/configure_console_sysvinit"
source "${DIR_LFS}/06_system_config/configure_console_systemd"
source "${DIR_LFS}/06_system_config/configure_rc_site"
source "${DIR_LFS}/06_system_config/configure_locale"
source "${DIR_LFS}/06_system_config/configure_inputrc"
source "${DIR_LFS}/06_system_config/configure_shells"
source "${DIR_LFS}/06_system_config/install_fonts"

source "${DIR_LFS}/07_make_system_bootable/configure_fstab"
source "${DIR_LFS}/07_make_system_bootable/configure_linux"
source "${DIR_LFS}/07_make_system_bootable/configure_grub"
source "${DIR_LFS}/07_make_system_bootable/finish_touch"


source "${DIR_BLFS}/do_blfs"

source "${DIR_BLFS}/01_after_lfs/configure_group_user"
source "${DIR_BLFS}/01_after_lfs/configure_skel"
source "${DIR_BLFS}/01_after_lfs/configure_profile"
source "${DIR_BLFS}/01_after_lfs/configure_issue"

source "${DIR_BLFS}/02_security/configure_sudo"
source "${DIR_BLFS}/02_security/configure_pwquality"
source "${DIR_BLFS}/02_security/configure_mit-kerberos5"
