#!/bin/bash

function	_printf()
{
	local	pad="${LIFOVAR_LOG_LVL[@]: -1}"
	local	pad_str=""

	if [ "${pad}" -gt 0 ]; then
		for ((i = 0; i < ${pad}; i++)); do
			pad_str+="   "
		done
	fi
	printf "[\e[33m%s\e[0m] " "$(date '+%d/%M/%Y %T')" >> ${LOG_FILE}
	printf "%s%b %b\n" "${pad_str}" "${1}" "${2}" | tee -a ${LOG_FILE}
}

function	ppass()
{ _printf "[\e[32m+\e[0m]" "${@}"; }

function	pfail()
{ _printf "[\e[31m-\e[0m]" "${@}"; }

function	pwarn()
{ _printf "[\e[31m!\e[0m]" "${@}"; }

function	pinfo()
{ _printf "[\e[34m*\e[0m]" "${@}"; }

function	ptitle()
{
	local	est_sbu="$(calc_sbu "${1}")"
	local	hdr="[\e[33;1m#\e[0;22m]"
	local	est_sbu_col="\e[32m"

	if [ "${est_sbu}" == "0" ]; then
		est_sbu="No Compilation"
		est_sbu_col="\e[31m"
	else
		est_sbu="SBU~:${est_sbu} ($(get_sbu ${est_sbu}))"
	fi
	est_sbu="$(printf "%-23s" "${est_sbu}")"
	est_sbu="${est_sbu_col}${est_sbu}\e[0m"
	_printf "${hdr}" "${est_sbu} ${@:2}"
}
