#!/bin/bash

function	_printf_ts()
{ printf "[${YEL}%s${RST}]" "$(date '+%d/%M/%Y %T')" >> ${LOG_FILE_EXEC}; }

function	_printf()
{
	local	pad="${LIFOVAR_LOG_LVL[@]: -1}"
	local	pad_str=""

	if [ "${pad}" -gt 0 ]; then
		for ((i = 0; i < ${pad}; i++)); do
			pad_str+="   "
		done
	fi
	if [ "${3:-}" == "" ]; then
		_printf_ts
		printf "%s%b %b\n" "${pad_str}" "${1}" "${2}" | tee -a ${LOG_FILE_EXEC}
	else
		printf "%b" "${2}" | tee -a ${LOG_FILE_EXEC}
	fi
}

function	ppass()
{ _printf "${HDR_PASS}" "${@}"; }

function	pfail()
{ _printf "${HDR_FAIL}" "${@}"; }

function	pwarn()
{ _printf "${HDR_WARN}" "${@}"; }

function	pinfo()
{ _printf "${HDR_INFO}" "${@}"; }

function	praw()
{
	_printf "" "${@}" "1"
}

function	ptitle()
{
	local	est_sbu="$(calc_sbu "${1}" "${2}")"
	local	hdr="${HDR_TITLE}"
	local	est_sbu_col="${GRE}"

	if [ "${est_sbu}" == "0" ]; then
		est_sbu="No Compilation"
		est_sbu_col="${RED}"
	else
		est_sbu="SBU~:${est_sbu} ($(get_sbu ${est_sbu}))"
	fi
	est_sbu="$(printf "%-23s" "${est_sbu}")"
	est_sbu="${est_sbu_col}${est_sbu}${RST}"
	_printf "${hdr}" "${est_sbu} ${@:3}"
}
