#!/bin/bash

function	save_last_step()
{
	for step in "${!STEP[@]}"; do
		if ! [[ "${step}" =~ ^STEP_ ]]; then
			local	cur_step="$(step_get_var "${step}")"
			if [ ${STEP[${step}]} -gt ${cur_step} ]; then
				pinfo "Saving last step for ${step} (${cur_step} -> ${STEP[${step}]})"
				step_set_var "${step}" "${STEP[${step}]}"
			fi
		fi
	done
}


function	trap_exit()
{
	LAST_RETURN_CODE=${LAST_RETURN_CODE:-${?}}
	if [ "${CTRL_C_PRESSED:-0}" == "1" ]; then
		pwarn "Interrupted by user"
	elif [ "${LAST_RETURN_CODE}" == "0" ]; then
		ppass "All steps done"
	else
		pfail "An error occured, error code: ${LAST_RETURN_CODE}"
	fi
	save_last_step
	daemon_kill
	unset ${!LFS_@} ${!DIR_@} ${!LOG_@} ${!SBU_@} ${!GET_PACK_@} ${!PACKAGE_@} \
		${!CURRENT_PACKAGE_@} ${!DAEMON_@} ${!S_@} \
		PATH_BASE LC_ALL CONFIG_SITE MAKEFLAGS CTRL_C_PRESSED
	# echo exit ${LAST_RETURN_CODE}
	exit ${LAST_RETURN_CODE}
}

function	trap_sigint()
{
	LAST_RETURN_CODE=${?}
	CTRL_C_PRESSED=1
	unset -n last_step step
	echo
	# echo sigint ${LAST_RETURN_CODE}
	exit ${LAST_RETURN_CODE}
}

trap trap_sigint SIGINT
trap trap_exit EXIT
