#!/bin/bash

function	trap_exit()
{
	LAST_RETURN_CODE=${LAST_RETURN_CODE:-${?}}
	if [ "${CTRL_C_PRESSED:-0}" == "1" ]; then
		pwarn "Interrupted by user"
	elif [ "${LAST_RETURN_CODE}" == "0" ]; then
		ppass "All steps done"
	else
		pfail "An error occured, error code: ${LAST_RETURN_CODE}"
	fi
	daemon_kill

	rm -rf /tmp/.{screen_size,daemon_out}.*

	unset ${!LFS_@} ${!DIR_@} ${!LOG_@} ${!SBU_@} ${!GET_PACK_@} ${!PACKAGE_@} \
		${!CURRENT_PACKAGE_@} ${!DAEMON_@} ${!S_@} \
		PATH_BASE LC_ALL CONFIG_SITE MAKEFLAGS CTRL_C_PRESSED
	# echo exit ${LAST_RETURN_CODE}
	exit ${LAST_RETURN_CODE}
}

function	trap_sigint()
{
	LAST_RETURN_CODE=${?}
	CTRL_C_PRESSED=1
	unset -n last_step step
	echo
	# echo sigint ${LAST_RETURN_CODE}
	exit ${LAST_RETURN_CODE}
}

trap trap_sigint SIGINT
trap trap_exit EXIT
