#!/bin/bash

# FUNCTIONS
function	_mkdir()
{ [ ! -d "${1}" ] && rm -vrf "${1}"; mkdir -vp "${1}"; }

function	take()
{ _mkdir ${1}; pushd ${1}; }

function	_printf()
{
	printf "[\e[33m%.13s\e[0m] " "$(date +%s%N)" >> ${LOG_FILE}
	printf "%b %b\n" "${1}" "${2}" | tee -a ${LOG_FILE}
}

function	ppass()
{ _printf "[\e[32m+\e[0m]" "${@}"; }

function	pfail()
{ _printf "[\e[31m-\e[0m]" "${@}"; }

function	pwarn()
{ _printf "[\e[31m!\e[0m]" "${@}"; }

function	pinfo()
{ _printf "[\e[34m*\e[0m]" "${@}"; }

function	get_sbu()
{ printf "%.6f\n" "$(echo "${1} * (${SBU:-1} / ${LFS_CORES:-1})" | bc -l)"; }

function	do_chroot()
{
	sudo chroot "/mnt/lfs" /usr/bin/env -i \
		HOME=/root \
		TERM="$TERM" \
		PS1='(lfs chroot) \u:\w\$ ' \
		PATH=/usr/bin:/usr/sbin \
		MAKEFLAGS="-j${LFS_CORES}" \
		TESTSUITEFLAGS="-j${LFS_CORES}" \
		/bin/bash <<<${@}
}

function	chroot_line()
{
	local	line="${1}"
	local	file="${2}"
	local	replace="${3:-0}"
	if [ "${replace}" == "1" ]; then
		replace=">"
	else
		replace=">>"
	fi

	sudo chroot "/mnt/lfs" /usr/bin/env -i \
		HOME=/root \
		TERM="$TERM" \
		PS1='(lfs chroot) \u:\w\$ ' \
		PATH=/usr/bin:/usr/sbin \
		MAKEFLAGS="-j${LFS_CORES}" \
		TESTSUITEFLAGS="-j${LFS_CORES}" \
		/usr/bin/bash <<<"echo '${line}' ${replace} ${file}"
}
